### DISCUSSION TITLE
PXE installation RHEL8.5 does not automatically start the O.S.

### DISCUSSION THREAD

**Discussion by pbvafer** [cobbler/cobbler#3122] [Version specific questions] [answered]
Version: `Cobbler 3.3.2`

I am installing RHEL 8.5 from a master PC to a client PC through a kickstart file, once the O.S. is installed. When the client PC restarts, it picks up the PXE-DHCP boot and tries to install again, having in `settings.yaml` the `pxe_just_once: true`, it does not send again the cobbler the URL with the installation and the screen stays black with '-' flashing. 

In the BIOS/UEFI I have enabled in boot mode: 
1- PXE
2- Disk 
For project reasons, I want to install as many times as I want an O.S. on the client PC. In `/var/lib/tftpboot/pxelinux.cfg` I have the file with the mac of the client PC with this content once the installation has been done:
```
totaltimeout 0
prompt 0
default nodo1
ontimeout nodo1
LABEL nodo1
        MENU LABEL nodo1
        localboot -1
```
The file is rewritten, before installation it looks like this: 
```
timeout 1
prompt 0
default nodo1
ontimeout nodo1
LABEL nodo1
        MENU LABEL nodo1
        kernel /images/RHEL8-x86_64/vmlinuz
        append initrd=/images/RHEL8-x86_64/initrd.img  kssendmac inst.ks=http://192.168.60.10/cblr/svc/op/autoinstall/system/nodo1
        ipappend 2
```
I have tried all the combinations in the BIOS/UEFI and it still doesn't work, I have tried entering `grubx64.efi` instead of `grubx86.efi` in `settings.yaml`. Also in `dhcp.template`, although I don't think this last one works for me because I have the DHCP and DNS server outside the master PC and Cobbler, I have it in a router inside a subnet.

If I change the BIOS/UEFI order manually, it does start the O.S. (RHEL 8.5 also) installed on the client PC, but if I leave it on automatically, it gets stuck, as I explained above.

**Comment by pbvafer** [comment]
This is the `settings.yaml` file:

```
# Cobbler settings file
# Docs for this file can be found at: https://cobbler.readthedocs.io/en/latest/cobbler-conf.html

allow_duplicate_hostnames: false
allow_duplicate_ips: false
allow_duplicate_macs: false
allow_dynamic_settings: false
always_write_dhcp_entries: false
anamon_enabled: false
auth_token_expiration: 3600
authn_pam_service: login
auto_migrate_settings: false
autoinstall: default.ks
autoinstall_snippets_dir: /var/lib/cobbler/snippets
autoinstall_templates_dir: /var/lib/cobbler/templates
bind_chroot_path: ''
bind_manage_ipmi: true
bind_master: 127.0.0.1
bind_zonefile_path: /var/named
boot_loader_conf_template_dir: /etc/cobbler/boot_loader_conf
bootloaders_dir: /var/lib/cobbler/loaders
bootloaders_formats:
  IA64: {binary_name: bootia64.efi}
  aarch64: {binary_name: grubaa64.efi}
  arm: {binary_name: bootarm.efi}
  arm64-efi:
    binary_name: grubaa64.efi
    extra_modules: [efinet]
  i386-efi: {binary_name: bootia32.efi}
  i386-pc-pxe:
    binary_name: grub.0
    extra_modules: [chain, pxe, biosdisk]
    mod_dir: i386-pc
  i686: {binary_name: bootia32.efi}
  powerpc-ieee1275:
    binary_name: grub.ppc64le
    extra_modules: [net, ofnet]
  x86_64-efi:
    binary_name: grubx64.efi
    extra_modules: [chain, efinet]
bootloaders_ipxe_folder: /usr/share/ipxe/
bootloaders_modules: [btrfs, ext2, xfs, jfs, reiserfs, all_video, boot, cat, configfile,
  echo, fat, font, gfxmenu, gfxterm, gzio, halt, iso9660, jpeg, linux, loadenv, minicmd,
  normal, part_apple, part_gpt, part_msdos, password_pbkdf2, png, reboot, search,
  search_fs_file, search_fs_uuid, search_label, sleep, test, 'true', video, mdraid09,
  mdraid1x, lvm, serial, regexp, tr, tftp, http, luks, gcry_rijndael, gcry_sha1, gcry_sha256]
bootloaders_shim_file: shim[a-zA-Z0-9]*\.efi
bootloaders_shim_folder: /boot/efi/EFI/*/
build_reporting_email: [root@localhost]
build_reporting_enabled: false
build_reporting_ignorelist: []
build_reporting_sender: ''
build_reporting_smtp_server: localhost
build_reporting_subject: ''
buildisodir: /var/cache/cobbler/buildiso
cheetah_import_whitelist: [random, re, time, netaddr]
client_use_https: false
client_use_localhost: false
cobbler_master: ''
convert_server_to_ip: false
createrepo_flags: -c cache -s sha
default_name_servers: []
default_name_servers_search: []
default_ownership: [admin]
default_password_crypted: psswd.
default_template_type: cheetah
default_virt_bridge: xenbr0
default_virt_disk_driver: raw
default_virt_file_size: 5
default_virt_ram: 512
default_virt_type: xenpv
enable_ipxe: false
enable_menu: true
grub2_mod_dir: /usr/lib/grub
grubconfig_dir: /var/lib/cobbler/grub_config
http_port: 80
include: [/etc/cobbler/settings.d/*.settings]
iso_template_dir: /etc/cobbler/iso
jinja2_includedir: /var/lib/cobbler/jinja2
kernel_options: {}
ldap_anonymous_bind: true
ldap_base_dn: DC=example,DC=com
ldap_port: 389
ldap_search_bind_dn: ''
ldap_search_passwd: ''
ldap_search_prefix: uid=
ldap_server: ldap.example.com
ldap_tls: true
ldap_tls_cacertdir: ''
ldap_tls_cacertfile: ''
ldap_tls_certfile: ''
ldap_tls_cipher_suite: ''
ldap_tls_keyfile: ''
ldap_tls_reqcert: ''
manage_dhcp: false
manage_dhcp_v4: false
manage_dhcp_v6: false
manage_dns: false
manage_forward_zones: []
manage_genders: false
manage_reverse_zones: []
manage_rsync: false
manage_tftpd: true
mgmt_classes: []
mgmt_parameters: {from_cobbler: true}
next_server_v4: 192.168.60.10
next_server_v6: ::ffff:c0a8:3c0a
nopxe_with_triggers: true
nsupdate_enabled: false
nsupdate_log: /var/log/cobbler/nsupdate.log
nsupdate_tsig_algorithm: hmac-sha512
nsupdate_tsig_key: [cobbler_update_key., key]
power_management_default_type: ipmilanplus
proxy_url_ext: ''
proxy_url_int: ''
puppet_auto_setup: false
puppet_parameterized_classes: true
puppet_server: ''
puppet_version: 2
puppetca_path: /usr/bin/puppet
pxe_just_once: true
redhat_management_key: ''
redhat_management_permissive: false
redhat_management_server: xmlrpc.rhn.redhat.com
register_new_installs: false
remove_old_puppet_certs_automatically: false
replicate_repo_rsync_options: -avzH
replicate_rsync_options: -avzH
reposync_flags: --newest-only --delete --refresh --remote-time
reposync_rsync_flags: -rltDv --copy-unsafe-links
restart_dhcp: true
restart_dns: true
run_install_triggers: true
samba_distro_share: DISTRO
scm_push_script: /bin/true
scm_track_author: cobbler <cobbler@localhost>
scm_track_enabled: false
scm_track_mode: git
serializer_pretty_json: false
server: 192.168.60.10
sign_puppet_certs_automatically: false
signature_path: /var/lib/cobbler/distro_signatures.json
signature_url: https://cobbler.github.io/signatures/3.0.x/latest.json
syslinux_dir: /usr/share/syslinux
syslinux_memdisk_folder: /usr/share/syslinux
syslinux_pxelinux_folder: /usr/share/syslinux
tftpboot_location: /var/lib/tftpboot
virt_auto_boot: true
webdir: /var/www/cobbler
webdir_whitelist: [misc, web, webui, localmirror, repo_mirror, distro_mirror, images,
  links, pub, repo_profile, repo_system, svc, rendered, .link_cache]
windows_enabled: false
windows_template_dir: /etc/cobbler/windows
xmlrpc_port: 25151
yum_distro_priority: 1
yum_post_install_mirror: true
yumdownloader_flags: --resolve
```

I have modified this parameter so that instead of looking for `grubx86.efi` it gets `grubx64.efi`, but it still doesn't work.
```
  x86_64-efi:
    binary_name: grubx64.efi
```

**Comment by pbvafer** [comment]
This is the `dhcp.template` file:

```
# ******************************************************************
# Cobbler managed dhcpd.conf file
#
# generated from cobbler dhcp.conf template ($date)
# Do NOT make changes to /etc/dhcpd.conf. Instead, make your changes
# in /etc/cobbler/dhcp.template, as /etc/dhcpd.conf will be
# overwritten.
#
# ******************************************************************

ddns-update-style interim;

allow booting;
allow bootp;

ignore client-updates;
set vendorclass = option vendor-class-identifier;

option space pxelinux;
option pxelinux.magic code 208 = string;
option pxelinux.configfile code 209 = text;
option pxelinux.pathprefix code 210 = text;
option pxelinux.reboottime code 211 = unsigned integer 32;
option system-arch code 93 = unsigned integer 16;

subnet 192.168.60.0 netmask 255.255.255.0 {
     option routers             192.168.60.10;
     option domain-name-servers 192.168.60.10;
     option subnet-mask         255.255.255.0;
     range dynamic-bootp        192.168.60.21 192.168.60.29;
     default-lease-time         21600;
     max-lease-time             43200;
     next-server                $next_server_v4;
     class "pxeclients" {
          match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";

          if option system-arch = 00:07 {
              filename "grub/BOOTX64.efi";
          }
          else {
              filename "pxelinux/pxelinux.0";
          }
    }
}

```

**Comment by pbvafer** [comment]
This is the image of the frame captured just before blocking, it happens very fast:
![IMG_20220530_101547](https://user-images.githubusercontent.com/79220152/171132003-3e0af204-5414-48d4-a0ca-27a560918aa9.jpg)

**Reply by SchoolGuy** [reply]
You mentioned in the issue we discussed before that if you select the disk manually that the system boots successfully. Is that still correct after all the things we checked?

**Reply by SchoolGuy** [reply]
I found the following in the syslinux wiki: https://wiki.syslinux.org/wiki/index.php?title=SYSLINUX#LOCALBOOT_type

**Reply by pbvafer** [reply]
Yes, it works if I change the boot order manually.

**Reply by pbvafer** [reply]
I would like to automate the system and not have to change it by hand every time, as the intention is to use it remotely.

**Reply by SchoolGuy** [reply]
Yes that is what Cobbler is indeed about. What you could try is change the value for localboot from `-1` to `0`, although according to the syslinux wiki that shouldn't be needed.

**Reply by pbvafer** [reply]
I'll try again, but I have already tried that change without success.

**Reply by SchoolGuy** [reply]
Oh okay but then something is wrong. Because according to the syslinux wiki this is exactly what you want. Did you try with other hardware?

**Reply by pbvafer** [reply]
![IMG_20220531_115317](https://user-images.githubusercontent.com/79220152/171147116-7b4e1721-effe-465c-865c-ff17bce5f6c2.jpg)

**Reply by pbvafer** [reply]
Sorry for the quality of the picture, after that it crashes, with `localboot 0`.

**Reply by pbvafer** [reply]
The next test is to replace the client PC with another one, to rule out hardware failures.

**Reply by pbvafer** [reply]
The model BIOS is: Z390 UD F10 GIGABYTE

**Reply by SchoolGuy** [reply]
Okay. I am sorry that I can't be of more help. I am out of ideas sadly... :/ From my point of view it should work.

**Comment by pbvafer** [comment, marked as answer]
@SchoolGuy After several days of research, it turns out that for some unknown reason, there are BIOS/UEFIs that are not compatible or ignore `localboot -1`. In order to be able to automate the boot of the O.S. in Cobbler ahead of PXE, I have modified the following files.

Replace `localboot -1` with:

```
sudo nano /etc/cobbler/boot_loader_conf/pxe.template
   #if $system_local
        COM32 chain.c32
        APPEND hd0
```

Copy the syslinux boot loaders:

```
sudo cp /usr/share/syslinux/chain.c32 /var/lib/cobbler/loaders/
sudo cp /usr/share/syslinux/libcom.c32 /var/lib/cobbler/loaders/
sudo cp /usr/share/syslinux/libutil.c32 /var/lib/cobbler/loaders/
```
And I'm not sure if this step is necessary, because now it works without modifying it but before it did not. Add to the end of the line `edd=off`.
```
sudo nano /etc/default/grub
    GRUB_CMDLINE_LINUX="crashkernel=auto resume=/dev/mapper/rhel-swap rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet edd=off"
```

**Reply by SchoolGuy** [reply]
Is there any way we can detect that those BIOS/UEFI is not compatible? Because it would be nice if we could automate that for everyone obviously.

**Reply by pbvafer** [reply]
I still don't have an answer for that, I don't know why it omits the `localboot -1` flag.

**Reply by pbvafer** [reply]
Supposedly `chain.c32` was used in older BIOS and is not valid for UEFI, now UEFI supports `localboot X`, my BIOS/UEFI is modern, it is in UEFI mode and not Legacy, but it recognizes `chain.c32` and not `localboot`.

**Reply by SchoolGuy** [reply]
You mentioned that you have a Z390 Chipset, right? Could it be that you have CSM enabled?

**Reply by pbvafer** [reply]
It is enabled, it is necessary to leave me the PXE option, if I disable it, PXE disappears.

**Reply by SchoolGuy** [reply]
Wait let me google that board you mentioned above. If the PXE stack it available for Legacy it must be for UEFI normally.

**Reply by SchoolGuy** [reply]
According to [the manual](https://download.gigabyte.com/FileList/Manual/mb_manual_z390-ud_v2_e.pdf?v=021eaf0e44271a7ec1a1544dcb4a5ee3), you should have two settings for PXE:

- Periphals -> Network Stack -> Ipv4/6 HTTP/PXE Support
- BIOS -> LAN PXE Boot Option ROM

What you want is the first option because the second option is just for legacy ROMs. What setting did you configure of those two?

**Reply by pbvafer** [reply]
I've actually tried both, the first option never worked for me, the second option was half working until yesterday.

**Reply by SchoolGuy** [reply]
Okay so I would try to disable CSM completely and try to get the first option working. Since you have modern hardware and modern OS there is no need for CSM except when you have very very old add-in cards (GPUs or RAID for example). If that option doesn't work then we need to fix that because I believe there we will find the root cause of the problem.

**Reply by pbvafer** [reply]
OK, I'll do the tests and let you know the results.

**Reply by pbvafer** [reply]
If I disable the CSM I lose the image on the PC, I understand that the graphics card is older than the motherboard and that's why I have never been able to test the first option successfully.

**Reply by pbvafer** [reply]
I also have no internal image, without GPU, and it forces me to reset the BIOS manually.

**Reply by pbvafer** [reply]
I am satisfied, because we have not only found the solution or patch, but we have also found the reason or problem, ideally we would like to replace the GPU with a more modern one.

**Reply by SchoolGuy** [reply]
Yes. I am not aware of your workload, so I can't help you choose the correct one. If you need help with another topic just open a discussion or issue again. :)

**Reply by pbvafer** [reply]
Thanks!

**Reply by zparihar** [reply]
Hi pbvafer,

Would you be able to post your:
- settings.yaml
- dhcpd.template
- a list of all Files for a UEFI boot to be successful

I'm having issues doing a UEFI PXE BOOT
(i can get pxelinux.0 bios boots no problem)

This would be much appreciated!

Cheers!

**Reply by pbvafer** [reply]
Hi zparihar, sorry for the delay.
I don't have a dhcpd.template configuration file as I have moved my dhcp server to an external router. But I attach my settings.yaml

```
# Cobbler settings file
# Docs for this file can be found at: https://cobbler.readthedocs.io/en/latest/cobbler-conf.html

allow_duplicate_hostnames: false
allow_duplicate_ips: false
allow_duplicate_macs: false
allow_dynamic_settings: false
always_write_dhcp_entries: false
anamon_enabled: false
auth_token_expiration: 3600
authn_pam_service: login
auto_migrate_settings: false
autoinstall: default.ks
autoinstall_snippets_dir: /var/lib/cobbler/snippets
autoinstall_templates_dir: /var/lib/cobbler/templates
bind_chroot_path: ''
bind_manage_ipmi: true
bind_master: 127.0.0.1
bind_zonefile_path: /var/named
boot_loader_conf_template_dir: /etc/cobbler/boot_loader_conf
bootloaders_dir: /var/lib/cobbler/loaders
bootloaders_formats:
  IA64: {binary_name: bootia64.efi}
  aarch64: {binary_name: grubaa64.efi}
  arm: {binary_name: bootarm.efi}
  arm64-efi:
    binary_name: grubaa64.efi
    extra_modules: [efinet]
  i386-efi: {binary_name: bootia32.efi}
  i386-pc-pxe:
    binary_name: grub.0
    extra_modules: [chain, pxe, biosdisk]
    mod_dir: i386-pc
  i686: {binary_name: bootia32.efi}
  powerpc-ieee1275:
    binary_name: grub.ppc64le
    extra_modules: [net, ofnet]
  x86_64-efi:
    binary_name: grubx86.efi
    extra_modules: [chain, efinet]
bootloaders_ipxe_folder: /usr/share/ipxe/
bootloaders_modules: [btrfs, ext2, xfs, jfs, reiserfs, all_video, boot, cat, configfile,
  echo, fat, font, gfxmenu, gfxterm, gzio, halt, iso9660, jpeg, linux, loadenv, minicmd,
  normal, part_apple, part_gpt, part_msdos, password_pbkdf2, png, reboot, search,
  search_fs_file, search_fs_uuid, search_label, sleep, test, 'true', video, mdraid09,
  mdraid1x, lvm, serial, regexp, tr, tftp, http, luks, gcry_rijndael, gcry_sha1, gcry_sha256]
bootloaders_shim_file: shim[a-zA-Z0-9]*\.efi
bootloaders_shim_folder: /boot/efi/EFI/*/
build_reporting_email: [root@localhost]
build_reporting_enabled: false
build_reporting_ignorelist: []
build_reporting_sender: ''
build_reporting_smtp_server: localhost
build_reporting_subject: ''
buildisodir: /var/cache/cobbler/buildiso
cheetah_import_whitelist: [random, re, time, netaddr]
client_use_https: false
client_use_localhost: false
cobbler_master: ''
convert_server_to_ip: false
createrepo_flags: -c cache -s sha
default_name_servers: []
default_name_servers_search: []
default_ownership: [admin]
default_password_crypted: $1$7tw5Hl8W$N5pbTotJ4OK6wA.h7FL9O.
default_template_type: cheetah
default_virt_bridge: xenbr0
default_virt_disk_driver: raw
default_virt_file_size: 5
default_virt_ram: 512
default_virt_type: xenpv
enable_ipxe: false
enable_menu: true
grub2_mod_dir: /usr/lib/grub
grubconfig_dir: /var/lib/cobbler/grub_config
http_port: 80
include: [/etc/cobbler/settings.d/*.settings]
iso_template_dir: /etc/cobbler/iso
jinja2_includedir: /var/lib/cobbler/jinja2
kernel_options: {}
ldap_anonymous_bind: true
ldap_base_dn: DC=example,DC=com
ldap_port: 389
ldap_search_bind_dn: ''
ldap_search_passwd: ''
ldap_search_prefix: uid=
ldap_server: ldap.example.com
ldap_tls: true
ldap_tls_cacertdir: ''
ldap_tls_cacertfile: ''
ldap_tls_certfile: ''
ldap_tls_cipher_suite: ''
ldap_tls_keyfile: ''
ldap_tls_reqcert: ''
manage_dhcp: false
manage_dhcp_v4: false
manage_dhcp_v6: false
manage_dns: false
manage_forward_zones: []
manage_genders: false
manage_reverse_zones: []
manage_rsync: false
manage_tftpd: true
mgmt_classes: []
mgmt_parameters: {from_cobbler: true}
next_server_v4: 192.168.60.10
next_server_v6: ::ffff:c0a8:3c0a
nopxe_with_triggers: true
nsupdate_enabled: false
nsupdate_log: /var/log/cobbler/nsupdate.log
nsupdate_tsig_algorithm: hmac-sha512
nsupdate_tsig_key: [cobbler_update_key., hvnK54HFJXFasHjzjEn09ASIkCOGYSnofRq4ejsiBHz3udVyGiuebFGAswSjKUxNuhmllPrkI0HRSSmM2qvZug==]
power_management_default_type: ipmilanplus
proxy_url_ext: ''
proxy_url_int: ''
puppet_auto_setup: false
puppet_parameterized_classes: true
puppet_server: ''
puppet_version: 2
puppetca_path: /usr/bin/puppet
pxe_just_once: true
redhat_management_key: ''
redhat_management_permissive: false
redhat_management_server: xmlrpc.rhn.redhat.com
register_new_installs: false
remove_old_puppet_certs_automatically: false
replicate_repo_rsync_options: -avzH
replicate_rsync_options: -avzH
reposync_flags: --newest-only --delete --refresh --remote-time
reposync_rsync_flags: -rltDv --copy-unsafe-links
restart_dhcp: true
restart_dns: true
run_install_triggers: true
samba_distro_share: DISTRO
scm_push_script: /bin/true
scm_track_author: cobbler <cobbler@localhost>
scm_track_enabled: false
scm_track_mode: git
serializer_pretty_json: false
server: 192.168.60.10
sign_puppet_certs_automatically: false
signature_path: /var/lib/cobbler/distro_signatures.json
signature_url: https://cobbler.github.io/signatures/3.0.x/latest.json
syslinux_dir: /usr/share/syslinux
syslinux_memdisk_folder: /usr/share/syslinux
syslinux_pxelinux_folder: /usr/share/syslinux
tftpboot_location: /var/lib/tftpboot
virt_auto_boot: true
webdir: /var/www/cobbler
webdir_whitelist: [misc, web, webui, localmirror, repo_mirror, distro_mirror, images,
  links, pub, repo_profile, repo_system, svc, rendered, .link_cache]
windows_enabled: false
windows_template_dir: /etc/cobbler/windows
xmlrpc_port: 25151
yum_distro_priority: 1
yum_post_install_mirror: true
yumdownloader_flags: --resolve
```
