### DISCUSSION TITLE
Can we support ubuntu 22.04 in future?

### DISCUSSION THREAD

**Discussion by mytxyang-arm** [cobbler/cobbler#3217] [General]
Ubuntu 22.04 was released already, do we have a plan to support it on cobbler?

**Comment by SchoolGuy** [comment]
@mytxyang-arm Feel free to open a PR with the modifications for `signatures.json` to this repo and the one for our GitHub Pages (https://github.com/cobbler/cobbler.github.io) and we should be good already. Cloud-Init support is missing but the legacy images should work. See https://github.com/cobbler/cobbler/issues/2339 for more detail.

For further investigation and planning additionally I have created #3218, however it is not required to support Ubuntu 22.04.

**Comment by opoplawski** [comment]
Are there legacy images for 22.04?  I'm not finding them.

**Reply by SchoolGuy** [reply]
I believe not anymore. I am finishing up the last cards for 3.4.0, thus it should come in approx one or two months if all things go well.

**Reply by btravouillon** [reply]
That's great news. Should we start to test dev release (from `main`) or is it too early? I can find someone in my team to perform such work.

**Reply by SchoolGuy** [reply]
@btravouillon it is too early sadly. I will ping here once I have News about this topic.

**Reply by Srylax** [reply]
> I believe not anymore. I am finishing up the last cards for 3.4.0, thus it should come in approx one or two months if all things go well.

@SchoolGuy Is this still the approximate release target for CloudInit support?

**Reply by SchoolGuy** [reply]
Version wise yes. I don't know if I can hold the date though. At work a lot of bugs poped up that needs to be put priority wise over feature development. I will do my best though.

**Reply by btravouillon** [reply]
Note that I am now able to deploy Ubuntu 22.04 with Cobbler 3.3 + workarounds to support the new installer, through an Ansible playbook. I may share this here if there is some interest.

**Reply by mytxyang** [reply]
Good news for ubuntu 22.04, so you use cloudinit solution to provisioning os? could you please share the ansible playbook? thanks.

**Reply by Niarff** [reply]
> Note that I am now able to deploy Ubuntu 22.04 with Cobbler 3.3 + workarounds to support the new installer, through an Ansible playbook. I may share this here if there is some interest.

Yes, can you share your scripts and workarounds ?

**Reply by btravouillon** [reply]
My notes are written into my native language so I have to translate.
First part is below, I will complete asap.

For the context, I must specify that I run [Cobbler 3.3.2 + some patches](https://github.com/cobbler/cobbler/compare/v3.3.2...btravouillon:cobbler:b3.3.2+patches) (backports) that are required for my setup. There is **no patch** to support Ubuntu 22.04 so any 3.3 should work.

First, I created a new distro by specifying the path to initrd and kernel files which were manually extracted from the ISO (no `cobbler import`, I use [this role](https://github.com/mila-iqia/ansible-role-cobbler) to manage Cobbler with Ansible).

```
root@cobblerlab:~# cobbler distro report --name ubuntu-22.04
Name                           : ubuntu-22.04
Architecture                   : x86_64
Automatic Installation Template Metadata : {'install_source_hostname': 'mirror.example.tld', 'install_source_directory': '/mirror/ubuntu/'}
TFTP Boot Files                : {}
Boot loaders                   : <<inherit>>
Breed                          : ubuntu
Comment                        : 
Fetchable Files                : {}
Initrd                         : /var/lib/tftpboot/ubuntu/22.04/ubuntu-installer/amd64/initrd
Kernel                         : /var/lib/tftpboot/ubuntu/22.04/ubuntu-installer/amd64/vmlinuz
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Management Classes             : []
OS Version                     : 
Owners                         : ['admin']
Redhat Management Key          : 
Remote Boot Initrd             : 
Remote Boot Kernel             : 
Template Files                 : {}
```

I also created a profile linked to the distro above, and a system linked to the profile.

Here is the PXE config file generated by Cobbler 3.3:
```
timeout 1
prompt 0
default jammy01
ontimeout jammy01
LABEL jammy01
        MENU LABEL jammy01
        kernel /images/ubuntu-22.04/vmlinuz
        append initrd=/images/ubuntu-22.04/initrd  auto-install/enable=true priority=critical netcfg/choose_interface=auto url=http://172.31.0.10/cblr/svc/op/autoinstall/system/jammy01 hostname=jammy01 domain=local.lan suite=
        ipappend 2
```

This file **does not work** with the new installer.
To make it work, one needs to:
 - add `autoinstall`
 - update `url` to provide an URL to the installation ISO (:warning: **this must be the ISO that initrd and vmlinuz were extracted from**. Do not mix 22.04.1 initrd/vmlinuz and 22.04.2 ISO)
 - add `ip=dhcp`
 - add `cloud-config-url=/dev/null` to download the ISO only once during the installation process
 - add `ds=nocloud-net;s=http://x.x.x.x/path/to/cloud-init-dir/` which should include answer files **user-data** and **meta-data**

So, the workaround is to:
 1) update the PXE config file to apply the changes above
 2) generate the **user-data** file from a template
 3) generate an empty **meta-data** file

**Reply by btravouillon** [reply]
## Update the PXE config file

It is possible to add the missing parts as Kernel Options in the profile.

```
root@cobblerlab:~# cobbler profile report --name cloud-vm-ubuntu-22.04 | grep Kernel
Kernel Options                 : {'autoinstall': '~', 'ip': 'dhcp', 'cloud-config-url': '/dev/null', 'url': 'http://mirror.example.tld/mirror/iso/ubuntu-22.04.2-live-server-amd64.iso'}
Kernel Options (Post Install)  : {}
```

With this, most of the parameters are defined when Cobbler templates the PXE config file. The next step is to update the URL to the **user-data** and **meta-data** files in `ds`.
I do this with this Ansible task:
```
    - name: Update PXELinux configuration file
      ansible.builtin.replace:
        path: "/srv/tftp/pxelinux.cfg/01-{{ mac_address }}"
        regexp: '^(\t+append.*)  auto-install.*url=([a-z0-9:/.]*) .*$'
        replace: '\1 ds=nocloud-net;s=\2/'
      delegate_to: cobblerlab
```

## Generate the **user-data** file from a template

Interestingly, the Cobbler service for the system will return the automatic installation file whatever the path **after** the system name. The URLs below will return the same file:

- http://172.31.0.10/cblr/svc/op/autoinstall/system/jammy01
- http://172.31.0.10/cblr/svc/op/autoinstall/system/jammy01/foo
- http://172.31.0.10/cblr/svc/op/autoinstall/system/jammy01/user-data

With this, it is possible to generate the **user-data** from a Cobbler template, as one would do for Kickstart or pre-seed installation.

A template could be `/var/lib/cobbler/templates/cloud-init-user-data`:
```
#cloud-config
autoinstall:
  identity:
    ## If hostname is not defined, use system name
    #if $getVar('hostname','') != ''
    #set $myhostname = $getVar('hostname')
    #else
    #set $myhostname = $getVar('system_name', 'cobbler').replace("_","-")
    #end if
    hostname: $myhostname
    password: $default_password_crypted
    username: ubuntu
  late-commands:
      ## Figure out if we're automating OS installation for a system or a profile
      #if $getVar('system_name','') != ''
      #set $what = "system"
      #else
      #set $what = "profile"
      #end if
    - wget "http://$http_server/cblr/svc/op/nopxe/$what/$name" -O /dev/null
  version: 1
```

```
root@cobblerlab:~# cobbler profile report --name cloud-vm-ubuntu-22.04 | grep 'Automatic Installation Template'
Automatic Installation Template : cloud-init-user-data
```

## Generate an empty **meta-data** file

By default, the URL http://172.31.0.10/cblr/svc/op/autoinstall/system/jammy01/meta-data will also return the automatic installation file.

To avoid this, edit the Apache configuration for Cobbler to add `AliasMatch ^/cblr/svc/.*/meta-data$ "/dev/zero"` so the server will always provide an empty file. For Debian, the config file is `/etc/apache2/conf-enabled/cobbler.conf`. Reload the service with `systemctl reload apache2`.

**Reply by btravouillon** [reply]
Here is the full task file I include in the Ansible playbooks used to deploy systems:
```
# This will create the system if it does not exist.
# To enable netboot, use `-e netboot_enabled=true`.
- name: Ensure the system exists in Cobbler
  community.general.cobbler_system:
    host: "{{ cobbler_api_host }}"
    use_ssl: "{{ cobbler_api_use_ssl }}"
    username: "{{ cobbler_api_username }}"
    password: "{{ cobbler_api_password }}"
    name: "{{ inventory_hostname }}"
    properties:
      netboot_enabled: "{{ netboot_enabled | default(omit) }}"
      profile: "{{ profile }}"
    interfaces: "{{ interfaces }}"
  delegate_to: localhost
  throttle: 1

# This block is a workaround to deploy Ubuntu with the new autoinstall tool.
# This is required until Cobbler add support of cloud-init deployments
# See https://github.com/cobbler/cobbler/issues/3218
- name: Workaround to deploy Ubuntu 22.04 LTS
  vars:
    _distro_query: "cobbler_profiles[?name=='{{ profile }}'].properties.distro"
  when:
    # Check the profile's distro in the Cobbler server's inventory
    - hostvars['cobblerlab'] | community.general.json_query(_distro_query) | first == 'ubuntu-22.04'
    # Do not apply the workaround if netboot is not requested
    - netboot_enabled is defined
    - netboot_enabled
  block:
    - name: Add AliasMatch to Apache2 config to answer with empty cloud-init meta-data file
      ansible.builtin.lineinfile:
        path: /etc/apache2/conf-available/cobbler.conf
        insertafter: '^AliasMatch'
        line: 'AliasMatch ^/cblr/svc/.*/meta-data$ "/dev/zero"'
      delegate_to: cobblerlab
      register: apache2_conf

    - name: Reload Apache2 configuration
      ansible.builtin.systemd:
        name: apache2
        state: reloaded
      when: apache2_conf.changed
      delegate_to: cobblerlab

    - name: Find MAC address of management interface
      ansible.builtin.set_fact:
        _mgmt_mac: |
          {% for iface in interfaces %}
          {% if interfaces[iface].management is defined and interfaces[iface].management %}
          {{ interfaces[iface].macaddress }}
          {% endif %}
          {% endfor %}

    - name: Update PXELinux configuration file
      ansible.builtin.replace:
        path: "/srv/tftp/pxelinux.cfg/01-{{ _mgmt_mac | trim | replace(':', '-') }}"
        regexp: '^(\t+append.*)  auto-install.*url=([a-z0-9:/.]*) .*$'
        replace: '\1 ds=nocloud-net;s=\2/'
      delegate_to: cobblerlab
```
