### DISCUSSION TITLE
cobbler3.2 install ubuntu 22.04 error

### DISCUSSION THREAD

**Discussion by QinQiang666** [cobbler/cobbler#3452] [Q&A]
in usr cobbler 3.2 install ubuntu 22.04 The following error occurred
![image](https://github.com/cobbler/cobbler/assets/29726716/46814094-474b-4b38-9540-7133735b2fa1)

**Comment by SchoolGuy** [comment]
Okay a couple of questions:

- How do your Distro, Profile and System look?
- How does the generated config for the system look in the DHCP server?
- Did you execute a `cobbler sync` already at least once?

**Reply by QinQiang666** [reply]
install centos7.9 Can be successful，install ubuntu An error occurred above
![image](https://github.com/cobbler/cobbler/assets/29726716/64ddd7b5-d54c-421c-9eae-0959ae416c8b)

Dhcp can obtain IP addresses

cobbler sync is ok
![image](https://github.com/cobbler/cobbler/assets/29726716/d5e83ed9-8c98-4b5a-a174-81dac5909b03)

**Reply by SchoolGuy** [reply]
Okay so you don't use systems. That is useful information. How does the PXE config look for the profile you are trying to install?

**Reply by QinQiang666** [reply]
profile The configuration is as follows
![image](https://github.com/cobbler/cobbler/assets/29726716/55ab0273-ff55-4d86-a4c8-86b6028c8e53)

cat /var/lib/cobbler/templates/ubuntu22.04.seed

d-i debian-installer/locale string en_US.UTF-8
d-i debian-installer/language string en
d-i debian-installer/country string US
d-i debian-installer/locale string en_US.UTF-8


d-i console-setup/ask_detect boolean false
d-i keyboard-configuration/xkb-keymap select us


d-i netcfg/choose_interface select auto
d-i netcfg/get_hostname string myhostname
d-i netcfg/get_domain string mydomain


d-i mirror/country string manual
d-i mirror/http/hostname string 192.168.161.178
d-i mirror/http/directory string /ubuntu
d-i mirror/http/proxy string


d-i passwd/root-login boolean false
d-i passwd/make-user boolean true
d-i passwd/user-fullname string My User
d-i passwd/username string myuser
d-i passwd/user-password password mypassword
d-i passwd/user-password-again password mypassword
d-i user-setup/allow-password-weak boolean true


d-i partman-auto/disk string /dev/sda
d-i partman-auto/method string regular
d-i partman-lvm/device_remove_lvm boolean true
d-i partman-md/device_remove_md boolean true
d-i partman-lvm/confirm boolean true
d-i partman-auto/choose_recipe select atomic
d-i partman/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true

**Reply by SchoolGuy** [reply]
@QinQiang666 That is not the PXE information. The PXE config can be found at `/srv/tftpboot/...` on most distros.

**Reply by QinQiang666** [reply]
@SchoolGuy 
this？
![image](https://github.com/cobbler/cobbler/assets/29726716/25dbc283-7dc4-498d-8005-56b18dff06ec)

This information was generated during the Cobbler import process

**Reply by SchoolGuy** [reply]
Yes exactly. So now you are interested in both the `grub` and `pxelinux.cfg` tree. That has configuration files that should match the names of your profile. The content of those would be interesting to me.

**Reply by QinQiang666** [reply]
@SchoolGuy 
![image](https://github.com/cobbler/cobbler/assets/29726716/43177573-00ea-49bf-a6ae-a9493ca1443d)

**Reply by SchoolGuy** [reply]
Unless you specifically disabled the `pxe` loader I believe you are missing the configuration data required to boot. However since in your first picture you show that the bootloader stage is passed already and you are showing a kernel error. As such I assume you are using grub to boot.

Still I would recommend you that you execute `cobbler sync` and try the installation again.

**Reply by QinQiang666** [reply]
Cobbler sync has been executed many times without any errors
![image](https://github.com/cobbler/cobbler/assets/29726716/815bae6d-bff3-4739-9265-5ea04a5977a6)
Reboot with pxe will also result in an error
![image](https://github.com/cobbler/cobbler/assets/29726716/7fdf80bf-7c24-4e80-9c00-0b85912e7c3a)
![image](https://github.com/cobbler/cobbler/assets/29726716/034b43a9-306c-4541-bdbf-210dc9b78ec5)

There is no problem booting the Centos7 system through pxe

**Reply by SchoolGuy** [reply]
Okay that is... interesting. If the `cobbler sync` is done successfully I don't have an idea what could cause this. Did you try older Ubuntu versions? Also, could it be that the before-mentioned scripts are causing this?

**Reply by QinQiang666** [reply]
This is also the case with Ubuntu version 20.04
I feel like I haven't finished loading the image information and haven't started executing the ks file content yet

**Reply by easpeagle** [reply]
I'm able to get 20.04 and 22.04 installed using autoinstall methods. This is just a development environment for me until better autoinstall support for ubuntu is baked into cobbler, so thankfully I don't have many systems yet... because after each cobbler sync, I have to manually edit the individual system grub configs here:

/var/lib/tftpboot/grub/system

I specifically change this line:

clinux /images/ubuntu-20.04/vmlinuz  autoinstall ip=dhcp cloud-config-url=/dev/null url=http://cblr-host/cobbler/iso/ubuntu-20.04.6-live-server-amd64.iso ds="nocloud-net;s=http://cblr-host/cobbler/ds/focal/"

Then, I make sure my user-data file is available at the indicated path in the ds parameter along with a zero-length vendor-data and meta-data file.

**Reply by QinQiang666** [reply]
@easpeagle 
My /var/lib/tftpboot/grub/system is a directory and the bottom is empty
![image](https://github.com/cobbler/cobbler/assets/29726716/f29339b7-1fc2-4ea6-8e33-102cc0aa6caa)
Should I modify the/var/lib/tftpboot/pxelinux.cfg/default file?
![image](https://github.com/cobbler/cobbler/assets/29726716/a5654b2d-7dfb-4288-a113-bbcd20a11dbc)

**Reply by QinQiang666** [reply]
@easpeagle  hi,I did not automatically use cloud init configuration after configuring the/var/lib/tftpboot/pxelinux.cfg/default file
![image](https://github.com/cobbler/cobbler/assets/29726716/7bad13b9-5ad0-4deb-94e7-1212be5e0308)
![image](https://github.com/cobbler/cobbler/assets/29726716/935e1ab0-a3b3-420e-a85c-38680d709d66)
Manual configuration is still required, no automated scripts have been executed
![image](https://github.com/cobbler/cobbler/assets/29726716/ad4c975d-262e-47a1-8921-1d2b628a3e8e)

**Reply by easpeagle** [reply]
@QinQiang666 ... yeah, I have to edit each and every grub configuration at this point, since support for this isn't baked in. That can be fairly easily scripted... This is what my grub line looks like:

```
clinux /images/ubuntu-20.04/vmlinuz autoinstall ip=dhcp cloud-config-url=/dev/null url=http://xxx.xxx.xxx.xxx/cobbler/iso/ubuntu-20.04.6-live-server-amd64.iso ds="nocloud-net;s=http://xxx.xxx.xxx.xxx/cobbler/ds/focal/"
```
This line is for focal, but I've done this with Jammy as well.

In that path `.../ds/focal` I have my autoinstall `user-meta` file and I just touched `meta-data` and `vendor-data` in that directory. Also note the quotes around the value of `ds=` ... it won't work without them.

**Reply by QinQiang666** [reply]
@easpeagle My automation installation always fails to read the user data file, I'm not sure if there's a problem with the file content
The file was copied from the installed machine
[root@mv161p178 iso]# cat user-data
#cloud-config
autoinstall:
  apt:
    disable_components: []
    geoip: true
    preserve_sources_list: false
    primary:
    - arches:
      - amd64
      - i386
      uri: http://mirrors.tuna.tsinghua.edu.cn/ubuntu
    - arches:
      - default
      uri: http://ports.ubuntu.com/ubuntu-ports
  drivers:
    install: false
  identity:
    hostname: mv161p209
    password: $6$LhhoWavOHBv6A2Tv$3tQbXS4lr67UD1YK8dC4uoytHeq.bgfLdEmtqknj0bPG84qklPg5eNg6.Qy3f0ZEDNrkfpi1HBC9801lTIFav/
    realname: bairong
    username: bairong
  kernel:
    package: linux-generic
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      eno1:
        addresses:
        - 192.168.161.209/22
        nameservers:
          addresses:
          - 202.106.0.20
          search: []
        routes:
        - to: default
          via: 192.168.163.1
      eno2:
        dhcp4: true
      eno3:
        dhcp4: true
      eno4:
        dhcp4: true
    version: 2
  source:
    id: ubuntu-server
    search_drivers: false
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  storage:
    layout:
      name: direct
  updates: security
  version: 1

**Comment by QinQiang666** [comment]
@easpeagle  Also, my server mode is configured in traditional mode and does not use UEFI. I am not sure if this has any impact
My initrd configuration is initrd=/images/ubuntu18.04 container x86_ 64/initrd, I think your configuration is/images/ubuntu-20.04/vmlinuz. Does this have an impact?
![image](https://github.com/cobbler/cobbler/assets/29726716/a4e6317d-82fc-4507-a934-b68a80d92763)

**Comment by QinQiang666** [comment]
@easpeagle I seem to know why there was no automatic installation. By checking the cloud init. log, I found that the default file used is the local/var/liv/cloud/seed/nocloud/user data file, which is empty
![image](https://github.com/cobbler/cobbler/assets/29726716/426ac01f-ba95-44c4-b09b-c881f761d64b)
How does Cobbler specify where to read user data files remotely? After modifying the boot file, what modifications do I need to make to the KS file of Cobbler's configuration?

**Reply by easpeagle** [reply]
Well, if you notice in my grub line, I'm pointing at a specific location in the URL. What I did was simply create a symlink to the real location. In my case:

```
ds="nocloud-net;s=http://xxx.xxx.xxx.xxx/cobbler/ds/focal/"
```
Looking at my apache config, I see this alias:

```
Alias /cobbler /var/www/cobbler
```
So, in `/var/www/cobbler` I created a symlink to the real location. It's that `ds=` bit that needs to point to the location where your `user-data` `meta-data` and `vendor-data` files live.

This is all a big hack because autoinstall just isn't supported in Cobbler yet.

**Reply by QinQiang666** [reply]
Yes, I also want to use this black technology approach to deploy the company's systems in bulk in the near future, and replace them after Cobbler supports it
Can I take a look at the contents of your user data meta data and vendor data files?

**Reply by easpeagle** [reply]
Eh... it's a pretty standard autoinstall... nothing special.
```
#cloud-config
autoinstall:
  apt:
    disable_components: []
    fallback: abort
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches:
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu
      - arches:
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    primary:
    - arches:
      - amd64
      - i386
      uri: http://us.archive.ubuntu.com/ubuntu
    - arches:
      - default
      uri: http://ports.ubuntu.com/ubuntu-ports
  drivers:
    install: false
  keyboard:
    layout: us
    toggle: null
    variant: ''
  late-commands:
  - curtin in-target --target=/target -- sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=""/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/' /etc/default/grub
  - curtin in-target --target=/target -- apt-get install -y ubuntu-desktop plymouth-theme-ubuntu-logo grub-gfxpayload-lists
  locale: en_US.UTF-8
  ssh:
    allow-pw: false
    authorized-keys: []
    install-server: true
  storage:
    config:
    # GPT on first disk found.
    - { ptable: gpt, wipe: superblock, preserve: false, name: '', grub_device: false, type: disk, id: disk0 }
    # Create EFI parition.
    - { device: disk0, size: 536870912, wipe: superblock, flag: boot, number: 1, preserve: false, grub_device: true, type: partition, id: partition-0 }
    - { fstype: fat32, volume: partition-0, preserve: false, type: format, id: format-0 }
    # Create boot partition.
    - { device: disk0, size: 1073741824, wipe: superblock, flag: '', number: 2, preserve: false, grub_device: false, type: partition, id: partition-1 }
    - { fstype: ext4, volume: partition-1, preserve: false, type: format, id: format-1 }
    # Create luks partition.
    - { device: disk0, size: -1, wipe: superblock, flag: '', number: 3, preserve: false, grub_device: false, type: partition, id: partition-2 }
    - { volume: partition-2, key: 'xxxxxxxxxxx', preserve: false, type: dm_crypt, id: luks_crypt }
    # Create LVM VG.
    - { name: rootvg, devices: [ luks_crypt ], preserve: false, type: lvm_volgroup, id: lvm_volgroup-0 }
    # Create Swap LV.
    - { name: swap, volgroup: lvm_volgroup-0, size: 4G, wipe: superblock, preserve: false, type: lvm_partition, id: lvm_partition-1 }
    - { fstype: swap, volume: lvm_partition-1, preserve: false, type: format, id: format-3 }
    # Create Root LV.
    - { name: root, volgroup: lvm_volgroup-0, size: -1, wipe: superblock, preserve: false, type: lvm_partition, id: lvm_partition-0 }
    - { fstype: ext4, volume: lvm_partition-0, preserve: false, type: format, id: format-2 }
    # Mount filesystems.
    - { path: '', device: format-3, type: mount, id: mount-3 }
    - { path: /, device: format-2, type: mount, id: mount-2 }
    - { path: /boot, device: format-1, type: mount, id: mount-1 }
    - { path: /boot/efi, device: format-0, type: mount, id: mount-0 }
  timezone: geoip
  updates: security
  user-data:
    hostname: yyyyyyyyyy
    users:
    - gecos: Ansible Ops Management
      groups:
      - users
      - adm
      lock-passwd: true
      name: ansible
      shell: /bin/bash
      ssh_authorized_keys:
      - <somekey>
      ssh_import_id: None
      sudo: ALL=(ALL) NOPASSWD:ALL
  version: 1
```
