### DISCUSSION TITLE
Cobbler3.3.7 installation of Ubuntu 22.04 does not go through the automatic installation process properly

### DISCUSSION THREAD

**Discussion by ShiroZhang** [cobbler/cobbler#3892] [Q&A]
After selecting the pxelinux.cfg option, it exits the automatic installation process and enters the manual installation interface.
When installing ubuntu 20.04 using the same method it is fine.
![image](https://github.com/user-attachments/assets/d87efa57-a81a-41da-9939-feca87930546)

**My profile setting**
```
Name                           : ubuntu2204-casper-x86_64
Automatic Installation Template : autoinstall-user-data
Automatic Installation Metadata : <<inherit>>
TFTP Boot Files                : <<inherit>>
Boot loaders                   : <<inherit>>
Comment                        : 
DHCP Tag                       : 
Distribution                   : ubuntu2204-casper-x86_64
Enable iPXE?                   : <<inherit>>
Enable PXE Menu?               : <<inherit>>
Fetchable Files                : <<inherit>>
DHCP Filename Override         : 
Kernel Options                 : {'url': 'http://192.168.100.28/cblr/pub/ubuntu-22.04.5-live-server-amd64.iso', 'ip': 'dhcp', 'autoinstall': '/var/lib/cobbler/templates/autoinstall-user-data'}
Kernel Options (Post Install)  : <<inherit>>
Parent boot menu               : 
Management Classes             : <<inherit>>
Management Parameters          : <<inherit>>
Name Servers                   : []
Name Servers Search Path       : []
Next Server (IPv4) Override    : <<inherit>>
Next Server (IPv6) Override    : <<inherit>>
Owners                         : <<inherit>>
Parent Profile                 : 
Proxy                          : <<inherit>>
Red Hat Management Key         : <<inherit>>
Repos                          : []
Server Override                : <<inherit>>
Template Files                 : {}
Virt Auto Boot                 : <<inherit>>
Virt Bridge                    : <<inherit>>
Virt CPUs                      : 1
Virt Disk Driver Type          : raw
Virt File Size(GB)             : <<inherit>>
Virt Path                      : 
Virt RAM (MB)                  : <<inherit>>
Virt Type                      : kvm

```

**/var/lib/cobbler/templates/autoinstall-user-data**
```
#cloud-config
# See the autoinstall documentation at:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - uri: http://mirrors.ustc.edu.cn/ubuntu/
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: false
  drivers:
    install: false
  identity:
    hostname: test-node
    password: $6$DgdCfUz7Xth3S.r3$fYE4FKpnvCSB0y0eY4vSxL1m4QKWzv2Lj9mczMo9zJOJ3Q8t5DqcKyFyUR8eA3TQ.RY0a77KJ3pQ0zlhqtIMg/
    realname: ubuntu
    username: ubuntu
  kernel:
    package: linux-generic
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      ens18:
        dhcp4: true
    version: 2
  oem:
    install: auto
  source:
    id: ubuntu-server
    search_drivers: false
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  storage:
    config:
    - ptable: gpt
      serial: 0QEMU_QEMU_HARDDISK_drive-scsi0
      path: /dev/sda
      wipe: superblock-recursive
      preserve: false
      name: ''
      grub_device: false
      id: disk-sda
      type: disk
    - device: disk-sda
      size: 1127219200
      wipe: superblock
      flag: boot
      number: 1
      preserve: false
      grub_device: true
      offset: 1048576
      path: /dev/sda1
      id: partition-0
      type: partition
    - fstype: fat32
      volume: partition-0
      preserve: false
      id: format-0
      type: format
    - device: disk-sda
      size: 106244866048
      wipe: superblock
      number: 2
      preserve: false
      grub_device: false
      offset: 1128267776
      path: /dev/sda2
      id: partition-1
      type: partition
    - fstype: ext4
      volume: partition-1
      preserve: false
      id: format-1
      type: format
    - path: /
      device: format-1
      id: mount-1
      type: mount
    - path: /boot/efi
      device: format-0
      id: mount-0
      type: mount
  updates: security
  version: 1
```

**/var/lib/tftpboot/pxelinux.cfg/default**
```

DEFAULT menu
PROMPT 0
MENU TITLE Cobbler | https://cobbler.github.io
TIMEOUT 200
TOTALTIMEOUT 6000
ONTIMEOUT local

LABEL local
        MENU LABEL (local)
        MENU DEFAULT
        LOCALBOOT -1

LABEL ubuntu2004-casper-x86_64
        MENU LABEL ubuntu2004-casper-x86_64
        kernel /images/ubuntu2004-casper-x86_64/vmlinuz
        append initrd=/images/ubuntu2004-casper-x86_64/initrd url=http://192.168.100.69/cblr/pub/ubuntu-20.04.6-live-server-amd64.iso autoinstall=/var/lib/cobbler/templates/autoinstall-user-data ip=dhcp  auto-install/enable=true priority=critical netcfg/choose_interface=auto url=http://192.168.100.69/cblr/svc/op/autoinstall/profile/ubuntu2004-casper-x86_64 hostname=ubuntu2004-casper-x8664 domain=local.lan suite=focal
        ipappend 2
LABEL ubuntu2204-casper-x86_64
        MENU LABEL ubuntu2204-casper-x86_64
        kernel /images/ubuntu2204-casper-x86_64/vmlinuz
        append initrd=/images/ubuntu2204-casper-x86_64/initrd url=http://192.168.100.28/cblr/pub/ubuntu-22.04.5-live-server-amd64.iso ip=dhcp autoinstall=/var/lib/cobbler/templates/autoinstall-user-data  auto-install/enable=true priority=critical netcfg/choose_interface=auto url=http://192.168.100.69/cblr/svc/op/autoinstall/profile/ubuntu2204-casper-x86_64 hostname=ubuntu2204-casper-x8664 domain=local.lan suite=jammy
        ipappend 2
MENU end
```
