### ISSUE TITLE
cobblerd startup fails on Debian 6 (Squeeze)

### ISSUE THREAD

**Issue by kaazoo** [cobbler/cobbler#118]
Installed Cobbler from git repository with version tag "cobbler-2.2.2-1" on Debian 6 (Squeeze) x64 Bit.

When starting cobblerd, I get the following exception:

```
root@cobbler# /usr/local/bin/cobblerd
Traceback (most recent call last):
  File "/usr/local/bin/cobblerd", line 76, in main
    api = cobbler_api.BootAPI(is_cobblerd=True)
  File "/usr/local/lib/python2.6/dist-packages/cobbler/api.py", line 130, in __init__
    self.deserialize()
  File "/usr/local/lib/python2.6/dist-packages/cobbler/api.py", line 873, in deserialize
    return self._config.deserialize()
  File "/usr/local/lib/python2.6/dist-packages/cobbler/config.py", line 266, in deserialize
    raise CX("serializer: error loading collection %s. Check /etc/cobbler/modules.conf" % item.collection_type())
CX: 'serializer: error loading collection settings. Check /etc/cobbler/modules.conf'
```

The config file modules.conf is existing and has the following contents:

```
root@cobbler# grep -v ^# /etc/cobbler/modules.conf 

[authentication]
module = authn_configfile

[authorization]
module = authz_allowall

[dns]
module = manage_bind

[dhcp]
module = manage_isc

[tftpd]
module = manage_in_tftpd
```

The settings file is also existing and has the following contents:

```
root@cobbler# grep -v ^# /etc/cobbler/settings

---
allow_duplicate_hostnames: 0

allow_duplicate_ips: 0

allow_duplicate_macs: 0

anamon_enabled: 0

build_reporting_enabled: 0
build_reporting_sender: ""
build_reporting_email: [ 'root@localhost' ]
build_reporting_smtp_server: "localhost"
build_reporting_subject: ""

cheetah_import_whitelist:
   - "random"
   - "re"
   - "time"

createrepo_flags: "-c cache -s sha"

default_kickstart: /var/lib/cobbler/kickstarts/default.ks

default_name_servers: []

default_ownership:
    - "admin"

default_password_crypted: "$1$mF86/UHC$WvcIcX2t6crBz2onWxyac."

default_virt_bridge: xenbr0

default_virt_file_size: 5

default_virt_ram: 512

default_virt_type: xenpv

enable_menu: 1

func_auto_setup: 0
func_master: overlord.example.org

http_port: 80

kernel_options:
    ksdevice: bootif
    lang: ' '
    text: ~

kernel_options_s390x:
    RUNKS: 1
    ramdisk_size: 40000
    root: /dev/ram0
    ro: ~
    ip: off
    vnc: ~

ldap_server: "ldap.example.com"
ldap_base_dn: "DC=example,DC=com"
ldap_port: 389
ldap_tls: 1
ldap_anonymous_bind: 1
ldap_search_bind_dn: ''
ldap_search_passwd: ''
ldap_search_prefix: 'uid='

mgmt_classes: []
mgmt_parameters:
   from_cobbler: 1

puppet_auto_setup: 0

sign_puppet_certs_automatically: 0

puppetca_path: "/usr/sbin/puppetca"

remove_old_puppet_certs_automatically: 0

manage_dhcp: 0

manage_dns: 0

manage_tftpd: 1

manage_rsync: 0

manage_forward_zones: []
manage_reverse_zones: []

next_server: 127.0.0.1

power_management_default_type: 'ipmitool'

power_template_dir: "/etc/cobbler/power"

pxe_just_once: 0

pxe_template_dir: "/etc/cobbler/pxe"

consoles: "/var/consoles"

redhat_management_type: "off"

redhat_management_server: "xmlrpc.rhn.redhat.com"

redhat_management_key: ""

redhat_management_permissive: 0

register_new_installs: 0

reposync_flags: "-l -m -d"

restart_dns: 1
restart_dhcp: 1

run_install_triggers: 1

scm_track_enabled: 0
scm_track_mode: "git"

server: cobbler.example.com

snippetsdir: /var/lib/cobbler/snippets

template_remote_kickstarts: 0

virt_auto_boot: 1

webdir: /var/www/cobbler

xmlrpc_port: 25151

yum_post_install_mirror: 1

yum_distro_priority: 1

yumdownloader_flags: "--resolve"
```
