### ISSUE TITLE
Debian_10: install from DEB fails

### ISSUE THREAD

**Issue by hbokh** [cobbler/cobbler#2238]
### Describe the bug

On Debian 10 "Buster", installing .DEB packages from [Pharaoh_Atem:/cobbler-dev/Debian_10/all/](https://download.opensuse.org/repositories/home:/Pharaoh_Atem:/cobbler-dev/Debian_10/all/) gives a non-working Cobbler. Cc @Conan-Kudo 

### To Reproduce

Install all requirements first:

```
# apt install tftpd-hpa createrepo rsync xorriso python3-cheetah python3-dns python3-future python3-ldap3 python3-netaddr python3-simplejson python3-tornado python3-django python-django-common python3-tz python3-dnsq 
```

1. `cd /var/cache/apt/archives/`
2. `wget https://download.opensuse.org/repositories/home:/Pharaoh_Atem:/cobbler-dev/Debian_10/all/cobbler_3.1.0~git.20191226.1577397150.c46abca1-15debian10.2_all.deb`
3. `wget https://download.opensuse.org/repositories/home:/Pharaoh_Atem:/cobbler-dev/Debian_10/all/cobbler-web_3.1.0~git.20191226.1577397150.c46abca1-15debian10.2_all.deb`
4. `dpkg -i cobbler_3.1.0~git.20191226.1577397150.c46abca1-15debian10.2_all.deb`
5. `dpkg -i cobbler-web_3.1.0~git.20191226.1577397150.c46abca1-15debian10.2_all.deb`

### Expected behavior

A working Cobbler 3.1.0 setup.

### Version

```
# cobbler --version
httpd does not appear to be running and proxying cobbler, or SELinux is in the way. Original traceback:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cobbler/cli.py", line 325, in check_setup
    s.ping()
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1187, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 404 Not Found>
```

Should have given `Cobbler 3.1.0`

### Screenshots

N.A.

#### Multiple errors:

During installation:
```txt
conffile '/etc/cobbler' is not a plain file
conffile '/var/lib/cobbler' is not a plain file
```
In file `/lib/systemd/system/cobblerd.service`:
```
ExecStart=/usr/local/bin/cobblerd -F
```
However file `cobblerd` is installed in `/usr/bin`. This seems to be an issue with `install_scripts` in `setup.py` (?).
Same goes for other files installed in `/usr/share`, where `cobblerd.service` points to `ExecStartPost=-/usr/bin/touch /usr/local/share/cobbler/web/cobbler.wsgi`.

The `postinst` has `openssl rand -base64 40 | sed 's/\//\\\//g'` in the `cobbler.spec`, but somehow this becomes `openssl rand -base64 40 | sed 's/\//\\//g'` (**lacking a backslash!**) in the .DEB-file.
This will give an error like this:
```
# openssl rand -base64 40 | sed 's/\//\\//g'
sed: -e expression #1, char 9: unknown option to `s'
139963333518464:error:02012020:system library:fflush:Broken pipe:../crypto/bio/bss_file.c:316:fflush()
139963333518464:error:20074002:BIO routines:file_ctrl:system lib:../crypto/bio/bss_file.c:318:
```

I build Cobbler 3.1.1 locally on Debian Buster with **debbuild** (`debbuild 19.11.0-0ubuntu18.04` and `debbuild-macros 0.0.2-0ubuntu18.04`).
It had the same issues.

**Comment by hbokh** [comment]
Some more issues while trying to build on Debian 10 "Buster".

### Issues

From `debbuild -vv -bb cobbler.spec` when building Cobbler 3.1.1 from the GitHub source tarball.

1.  Apache2 config

```
/bin/cp: cannot stat '/root/debbuild/BUILDROOT/cobbler-3.1.1-1debian10.amd64/etc/apache2/conf.d/cobbler.conf': No such file or directory
```

Path is `conf-available`, **not** `conf.d`:

```
# ls -al /root/debbuild/BUILDROOT/cobbler-3.1.1-1debian10.amd64/etc/apache2/conf-available/
total 16
drwxr-xr-x 2 root root 4096 Jan 15 09:44 .
drwxr-xr-x 3 root root 4096 Jan 15 09:44 ..
-rw-r--r-- 1 root root  994 Jan 15 09:44 cobbler.conf
-rw-r--r-- 1 root root 1110 Jan 15 09:44 cobbler_web.conf
```

2. Syntax errors from `sh` in the late state of the `debbuild`

```
--- cut --- 8< ---
Checking library requirements...
Executing (package-creation): /bin/sh -e /var/tmp/deb-tmp.pkg.71103 for cobbler
+ umask 022
+ cd /root/debbuild/BUILD
+ /usr/bin/fakeroot -- /usr/bin/dpkg-deb -b /root/debbuild/BUILDROOT/cobbler-3.1.1-1debian10.amd64/main /root/debbuild/DEBS/all/cobbler_3.1.1-1debian10_all.deb
dpkg-deb: warning: conffile '/etc/cobbler' is not a plain file
dpkg-deb: warning: conffile '/var/lib/cobbler' is not a plain file
dpkg-deb: warning: ignoring 2 warnings about the control file(s)
dpkg-deb: building package 'cobbler' in '/root/debbuild/DEBS/all/cobbler_3.1.1-1debian10_all.deb'.
+ exit 0
sh: 1: Syntax error: "(" unexpected
sh: 1: Syntax error: "(" unexpected
Checking library requirements...
Executing (package-creation): /bin/sh -e /var/tmp/deb-tmp.pkg.65027 for cobbler-web
+ umask 022
+ cd /root/debbuild/BUILD
+ /usr/bin/fakeroot -- /usr/bin/dpkg-deb -b /root/debbuild/BUILDROOT/cobbler-3.1.1-1debian10.amd64/cobbler-web /root/debbuild/DEBS/all/cobbler-web_3.1.1-1debian10_all.deb
dpkg-deb: building package 'cobbler-web' in '/root/debbuild/DEBS/all/cobbler-web_3.1.1-1debian10_all.deb'.
+ exit 0
```

Also the `dpkg-deb: warning: conffile`.

### Fixes

**Add. 1**

Change https://github.com/cobbler/cobbler/blob/master/cobbler.spec#L39 from `conf.d` to `conf-available`.

**Other**

I fixed the sed error for the `RAND_SECRET` by replacing https://github.com/cobbler/cobbler/blob/master/cobbler.spec#L319 with 
`RAND_SECRET=$(python3 -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())")`

**Comment by hbokh** [comment]
Another issue in https://github.com/cobbler/cobbler/blob/master/config/cobbler/settings#L441

Line should have 2x double quotes `proxy_url_ext: ""` (just as is done for `proxy_url_int: ""` on line 447), or augeas will fail replacing values.
See this lens: https://github.com/hercules-team/augeas/blob/master/lenses/cobblersettings.aug

Tested with `augmatch -l cobblersettings /etc/cobbler/settings`.

**Comment by SchoolGuy** [comment]
@hbokh But wouldn't that convert the type of the settings? I mean, if used, you have two suboptions... To fix this wouldn't it be better to set the suboptions to `""`

**Comment by hbokh** [comment]
@SchoolGuy 
I'm trying to do an upgrade from Cobbler 2.6.11 on Debian Jessie to Cobbler 3.1.1 on Debian Buster.

The way the "cobblersettings" augeas lens was written, complies with the "older Cobbler".
See `release26` https://github.com/cobbler/cobbler/blob/release26/config/settings#L458 

The way it is now for `proxy_url_*t` is inconsistent IMHO.

**Comment by SchoolGuy** [comment]
@hbokh Sounds good. We are trying to build it with debbuild but I am struggling. And yes it may be but sadly we have to put out fires on every end of cobbler so I can't say when I can look at this. If you think it is valuable then open an issue as a feature request.

**Comment by hbokh** [comment]
@SchoolGuy I can add a PR with my changes from everything above.
ATM I have what looks like a usable Cobbler 3.1.1 on Buster, but I have to change things after install.
As said using SaltStack. This is what I apply to get it to work (self-explanatory):

```yaml
### TEMP ######################################################################
# The directory and file below need to exist or the package fails to install...
/var/lib/cobbler/collections:
  file.directory:
    - group: root
    - dir_mode: '0755'
    - makedirs: True

/etc/cobbler/auth.conf:
  file.managed:
    - source: salt://cobbler/files/auth.conf
    - user: root
    - group: root
    - mode: '0644'
    - makedirs: True

# Use custom build Cobbler DEBs, put in /var/cache/apt/archives/
cobbler:
  pkg.installed:
    - sources:
      - cobbler: /var/cache/apt/archives/cobbler_3.1.1-1debian10_all.deb
  service.running:
    - name: cobblerd
    - enable: True

cobbler-web:
  pkg.installed:
    - sources:
      - cobbler-web: /var/cache/apt/archives/cobbler-web_3.1.1-1debian10_all.deb
  require:
    - pkg: cobbler

# install_scripts in setup.py screwed up for package build, hence dirty fix here
cobblerd-symlink:
  file.symlink:
    - name: /usr/local/bin/cobblerd
    - target: /usr/bin/cobblerd
    - force: True

share-cobbler-symlink:
  file.symlink:
    - name: /usr/local/share/cobbler
    - target: /usr/share/cobbler
    - force: True
### END TEMP ##################################################################
```

The (pre-)added directory and file are probably the result of these errors in the `debbuild`:
```
dpkg-deb: warning: conffile '/etc/cobbler' is not a plain file
dpkg-deb: warning: conffile '/var/lib/cobbler' is not a plain file
```

The symlinks in `/usr/local/` are needed for the systemd.service to work. The solution for thi s might be in the `setup.py` or can be overruled with a `debbuild` macro in `~/.debmacros`. Not sure about this though.
