### ISSUE TITLE
How to make a whole playbook, including vars_prompt, run sequentially on all the target hosts

### ISSUE THREAD

**Issue by ShrutiChavali** [cobbler/cobbler#2521]
### Version

````paste below
ansible:~ # cobbler --version
Cobbler 2.9.0
  source: b**, b'Mon Feb 18 16:08:42 2019 +0100'
  build time: Wed Feb 20 18:17:47 2019
````

### Question

I have a network playbook, which assigns IP to 3 network interface cards on VM (ens192 is already set during VM creation). 

```
---
- name: networking
  hosts: all
  remote_user: root
  gather_timeout: 20
  gather_facts: yes

  vars_prompt:
    - name: ip_eth1
      prompt: "IP for eth1 interface: "
      private: no
    - name: ip_eth2
      prompt: "IP for eth2 interface: "
      private: no

  tasks:
  - name: nmcli add Ethernet - conn_name only & ip4 gw4
    nmcli:
        type: ethernet
        conn_name: '{{ item.name }}'
        ifname: '{{ item.name }}'
        ip4: '{{ item.ipaddr }}/16'
        #gw4: '{{ item.gw4 }}'
        state: present
    loop:
    - { name: 'ens224', ipaddr: '{{ ip_eth1 }}', netmask: '255.255.240.0' }
    - { name: 'ens256', ipaddr: '{{ ip_eth2 }}', netmask: '255.255.240.0' }
```

And I want to run this playbook on 2 hosts (node1, node2) at the same time, as below:
`# ansible-playbook -i inventory network_setup.yml -l node1, node2 -vv`

I tried using serial: 1 at the start of the playbook, but only the tasks part runs sequentially on each host, but the vars_prompt appears only once. So same 2 ips are getting set on both the machines. Any way I could make this work?
