### ISSUE TITLE
PXE Boot failing - TFTP Error - File not found - grub.0 with manage_dhcp enabled

### ISSUE THREAD

**Issue by marbaa** [cobbler/cobbler#2844]
### Describe the bug

PXE boot is failing with messages:

- PXE-T01: File not found
- PXE-E3B: TFTP Error - File Not Found
- PXE-M0F: Exiting Intel PXE ROM

It is failing when manage_dhcp is enabled, beacuse it is searching for grub/grub.0 file which doesn't exists anywhere on the filesystem.

```
[root@thecobbler8 cobbler]# find / | grep --color grub\.0
[root@thecobbler8 cobbler]#
```

**dhcp.template**
```
     class "pxeclients" {
          match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";

          # Legacy
          if option system-arch = 00:00 {
              filename "grub/grub.0";
          }
          # UEFI-32-1
          if option system-arch = 00:06 {
               # Not supported, no 32 bit UEFI grub executable
              filename "unsupported";
          }
...
          else if option system-arch = 00:0e {
              filename "grub/grub.ppc64le";
          }
          else
          {
              filename "grub/grub.0";
          }
```

**dhcp.template from Cobbler 2.8.5**
```
class "pxeclients" {
          match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";
          if option pxe-system-type = 00:02 {
                  filename "ia64/elilo.efi";
          } else if option pxe-system-type = 00:06 {
                  filename "grub/grub-x86.efi";
          } else if option pxe-system-type = 00:07 {
                  filename "grub/grub-x86_64.efi";
          } else if option pxe-system-type = 00:09 {
                  filename "grub/grub-x86_64.efi";
          } else {
                  filename "pxelinux.0";
          }
     }
```

### Steps to reproduce

1. Install any Centos 8.x/Stream/RHEL8x
2. Install Cobbler from repository
3. Enable manage_dhcp in cobbler.yaml
4. Import any Centos7.x/RHEL7.x iso or any Centos8.x/RHEL8.x iso

### Expected behavior

I've expected to automatically start PXE boot

### Cobbler version

````paste below
Cobbler 3.2.2
````

### Operating system

````
CentOS Stream release 8
````

### Cobbler log

````paste below
````

**Comment by marbaa** [comment]
Cobbler 3.2.2, maybe whole 3.x is working weirdly. During cobbler import, it doesn't import pxelinux.0 to /var/lib/tftpboot. I tried to specify only: ```filename "pxelinux.0";``` to **dhcp.template**, manually ```cp /usr/share/syslinux/pxelinux.0 /var/lib/tftpboot``` but now, it is failing with ```Failed to load ldlinux.c32```. This file is not present anywhere under cobbler directories, only in ```/usr/share/syslinux/ldlinux.c32```. Comparing to Cobbler 2.8.5 on Centos7.9 it is only under ```cobbler/ks_mirror``` directory ```/var/www/cobbler/ks_mirror/RedHat8.5-x86_64/isolinux/ldlinux.c32``` which is (the ks_mirror directory) however not present under Cobbler 3.x.

So right now, I wonder if it is working for anybody, because according my tests it shouldn't work for nobody.

**Comment by marbaa** [comment]
Okay, workaround from [other issue](https://github.com/cobbler/cobbler/issues/2708#issuecomment-878206696 by manually copying files helped. That is still not documented on docu page :).

So lets focus on the issue title, the missing grub.0 file.

**Comment by SchoolGuy** [comment]
So the problem you have could be similar to: https://github.com/cobbler/cobbler/issues/2372

**Comment by marbaa** [comment]
Exactly. I was searching any issue regarding grub.0 but github didn't find anything for me.
So, I'm adding step executing
```
/usr/share/cobbler/bin/mkgrub.sh
```
as another step to my internal docu for cobbler 3.x.

This step, and manually copying files from
```
/usr/share/syslinux/{ldlinux.c32,libcom32.c32,libutil.c32,menu.c32,pxelinux.0}
```
could be automated by cobbler sync, I believe.

**Comment by SchoolGuy** [comment]
With the current `master` version there is a new command called `cobbler mkloaders` which automates this step. Since it is not required for every sync it was decided currently that we don't include it in the `cobbler sync` process.

**Comment by pkqsun** [comment]
@SchoolGuy 
I met the same issue for version 3.2.2.

```
[root@pkq:/etc/cobbler]$ cobbler mkloaders 
task started: 2022-04-02_104625_mkloaders
task started (id=Create bootable bootloader images, time=Sat Apr  2 10:46:25 2022)
running python triggers from /var/lib/cobbler/triggers/task/mkloaders/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/mkloaders/pre/*
shell triggers finished successfully
Unable to find "shim.efi" file. Please adjust "bootloaders_shim_file" regex. Bailing out of linking the shim!
ipxe directory did not exist. Please adjust the "bootloaders_ipxe_folder". Bailing out of iPXE setup!
GRUB2 modules directory for arch "IA64" did no exist. Skipping GRUB2 creation
GRUB2 modules directory for arch "aarch64" did no exist. Skipping GRUB2 creation
GRUB2 modules directory for arch "arm" did no exist. Skipping GRUB2 creation
GRUB2 modules directory for arch "arm64-efi" did no exist. Skipping GRUB2 creation
GRUB2 modules directory for arch "i386-efi" did no exist. Skipping GRUB2 creation
GRUB2 modules directory for arch "i386-pc-pxe" did no exist. Skipping GRUB2 creation
GRUB2 modules directory for arch "i686" did no exist. Skipping GRUB2 creation
GRUB2 modules directory for arch "powerpc-ieee1275" did no exist. Skipping GRUB2 creation
GRUB2 modules directory for arch "x86_64-efi" did no exist. Skipping GRUB2 creation
*** TASK COMPLETE ***
```
```
bootloaders_dir: /var/lib/cobbler/loaders
bootloaders_formats:
  IA64:
    binary_name: bootia64.efi
  aarch64:
    binary_name: grubaa64.efi
  arm:
    binary_name: bootarm.efi
  arm64-efi:
    binary_name: grubaa64.efi
    extra_modules:
    - efinet
  i386-efi:
    binary_name: bootia32.efi
  i386-pc-pxe:
    binary_name: grub.0
    extra_modules:
    - chain
    - pxe
    - biosdisk
    mod_dir: i386-pc
  i686:
    binary_name: bootia32.efi
  powerpc-ieee1275:
    binary_name: grub.ppc64le
    extra_modules:
    - net
    - ofnet
  x86_64-efi:
    binary_name: grubx86.efi
    extra_modules:
    - chain
    - efinet
bootloaders_ipxe_folder: /usr/share/ipxe/
```
I did not change above section of /etc/cobbler/settings.yaml and cobbler sync also finished successfully.
There is still no file of /var/lib/tftpboot/grub/grub.0.

Just wonder for x86_64 Legacy mode, am I missing anything?


```
class "pxeclients" {
          match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";

          # Legacy
          if option system-arch = 00:00 {
              filename "grub/grub.0";
          }

```
