### ISSUE TITLE
setting network interface using xmlrpc not working

### ISSUE THREAD

**Issue by th-2021** [cobbler/cobbler#2846]
### Describe the bug

When adding/modifying a system to add an interface eth0, only a default interface is created and the eth0 is missing

### Steps to reproduce

1. Using ansible cobbler_system or prov.py (https://github.com/HarrisonTotty/prov) with an interface eth0
2. cobbler system report only shows a default interface
3.

### Expected behavior

There should also be an entry with eth0

### Cobbler version

````paste below
3.3.1 (github/master)
````

### Operating system

OpenSuse 15.3

### Cobbler log

````paste below
````
No error shown

### Additional information

The file I used for prov.py has:
```yaml
systems:
  th-vm-11:
    interfaces:
      eth0:
        dns_name: 'th-vm-11.labnet.hpe'
        mac_address: '01:02:03:04:05:06'
        management: true
    mgmt_classes:
    - hanahosts
    profile: sles12sp5-x86_64
```

The interface shown by cobbler system report:
```
Interface =====                : default
Bonding Opts                   :
Bridge Opts                    :
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       :
DNS Name                       :
Per-Interface Gateway          :
Master Interface               :
Interface Type                 : NA
IP Address                     :
IPv6 Address                   :
IPv6 Default Gateway           :
IPv6 MTU                       :
IPv6 Prefix                    :
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    :
Management Interface           : False
MTU                            :
Subnet Mask                    :
Static                         : False
Static Routes                  : []
Virt Bridge                    : xenbr0
```
No eth0. 

BTW https://github.com/HarrisonTotty/prov is a nice tool to test xmlrpc with cobbler. Maybe it should mentioned in the docs somewhere.
