### ISSUE TITLE
Installation Loop despite having netboot enabled set to false

### ISSUE THREAD

**Issue by Simssnig** [cobbler/cobbler#3329]
### Describe the bug

We are installing a baremetal Server (shuttle XPC nano NC10U) with Rocky9. 
PXE Boot is enabled and has precedence over booting the local disk.
After the installation of the baremetal server is completed the target reboots using PXE again. 
Instead of ending up booting from the local disk the installation starts over. System stays in an installation loop.

### Steps to reproduce

1. The Shuttle is added to cobbler system
```
/usr/bin/cobbler system add --name=shuttle-sbl.lab.local --hostname=shuttle-sbl.lab.local --profile=rocky9-x86_64 --name-servers="1.1.1.1 8.8.8.8" --gateway=192.168.31.1 --interface=eth0 --mac-address=80:ee:73:f3:8e:f9 --ip-address=192.168.31.125 --netboot-enabled=1 --netmask=255.255.255.0 --name-servers-search=lab.local --dns-name=shuttle-sbl.lab.local --static=1 --autoinstall-meta="netmask_prefix=24 install_disk=nvme0n1"
```
2. Cobbler starts with the installation
Inside cobbler the shuttle system looks as following. Netboot is indeed enabled.
```
Name                           : shuttle-sbl.lab.local
Automatic Installation Template : <<inherit>>
Automatic Installation Template Metadata : {'netmask_prefix': '24', 'install_disk': 'nvme0n1'}
TFTP Boot Files                : <<inherit>>
Boot loaders                   : <<inherit>>
Comment                        :
Enable iPXE?                   : <<inherit>>
Fetchable Files                : <<inherit>>
DHCP Filename Override         : <<inherit>>
Gateway                        : 192.168.31.1
Hostname                       : shuttle-sbl.lab.local
Image                          :
IPv6 Autoconfiguration         : False
IPv6 Default Device            :
Kernel Options                 : <<inherit>>
Kernel Options (Post Install)  : <<inherit>>
Management Classes             : <<inherit>>
Management Parameters          : <<inherit>>
Name Servers                   : ['1.1.1.1', '8.8.8.8']
Name Servers Search Path       : ['lab.local']
Netboot Enabled                : True
Next Server (IPv4) Override    : <<inherit>>
Next Server (IPv6) Override    : <<inherit>>
Owners                         : <<inherit>>
Power Management Address       :
Power Management ID            :
Power Identity File            :
Power Management Options       :
Power Management Password      :
Power Management Type          :
Power Management Username      :
Profile                        : rocky9-x86_64
Internal Proxy                 : <<inherit>>
Redhat Management Key          : <<inherit>>
Repos Enabled                  : False
Serial Baud Rate               : -1
Serial Device #                : -1
Server Override                : <<inherit>>
Status                         :
Template Files                 : {}
Virt Auto Boot                 : <<inherit>>
Virt CPUs                      : <<inherit>>
Virt Disk Driver Type          : <<inherit>>
Virt File Size(GB)             : <<inherit>>
Virt Path                      : <<inherit>>
Virt PXE Boot                  : False
Virt RAM (MB)                  : <<inherit>>
Virt Type                      : <<inherit>>
Interface =====                : default
Bonding Opts                   :
Bridge Opts                    :
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       :
DNS Name                       :
Per-Interface Gateway          :
Master Interface               :
Interface Type                 : NA
IP Address                     :
IPv6 Address                   :
IPv6 Default Gateway           :
IPv6 MTU                       :
IPv6 Prefix                    :
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    :
Management Interface           : False
MTU                            :
Subnet Mask                    :
Static                         : False
Static Routes                  : []
Virt Bridge                    :
Interface =====                : eth0
Bonding Opts                   :
Bridge Opts                    :
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       :
DNS Name                       : shuttle-sbl.lab.local
Per-Interface Gateway          :
Master Interface               :
Interface Type                 : NA
IP Address                     : 192.168.31.125
IPv6 Address                   :
IPv6 Default Gateway           :
IPv6 MTU                       :
IPv6 Prefix                    :
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    : 80:ee:73:f3:8e:f9
Management Interface           : False
MTU                            :
Subnet Mask                    : 255.255.255.0
Static                         : True
Static Routes                  : []
Virt Bridge                    :
```
3. After the first installation is completed, cobbler sets the Netboot Enabled Flag to False. The shuttle reboots and restarts the installation.

### Expected behavior

A system with netboot enabled set to false should boot from the local disk.
 
### Cobbler version

````
Cobbler 3.3.2
  source: ?, ?
  build time: Wed May  4 01:38:10 2022
````

### Operating system

```
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```
### Cobbler log

````paste below
[Thread-1362] 2023-01-18T11:17:26 - DEBUG | REMOTE CLI Authorized; user(?)
[Thread-1363] 2023-01-18T11:21:53 - INFO | REMOTE generate_autoinstall; user(?)
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/network_config/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/network_config/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/network_config/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/network_config/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/network_config/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/network_config/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/log_ks_pre/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/log_ks_pre/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/log_ks_pre/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/log_ks_pre/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/log_ks_pre/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/log_ks_pre/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/autoinstall_start/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/autoinstall_start/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/autoinstall_start/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/autoinstall_start/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/autoinstall_start/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/autoinstall_start/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/pre_install_network_config/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/pre_install_network_config/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/pre_install_network_config/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/pre_install_network_config/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/pre_install_network_config/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/pre_install_network_config/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/pre_anamon/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/pre_anamon/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/pre_anamon/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/pre_anamon/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/pre_anamon/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/pre_anamon/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/log_ks_post_nochroot/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/log_ks_post_nochroot/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/log_ks_post_nochroot/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/log_ks_post_nochroot/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/log_ks_post_nochroot/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/log_ks_post_nochroot/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/log_ks_post/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/log_ks_post/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/log_ks_post/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/log_ks_post/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/log_ks_post/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/log_ks_post/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/post_install_kernel_options/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/post_install_kernel_options/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/post_install_kernel_options/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/post_install_kernel_options/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/post_install_kernel_options/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/post_install_kernel_options/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/post_install_network_config_arc/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/post_install_network_config_arc/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/post_install_network_config_arc/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/post_install_network_config_arc/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/post_install_network_config_arc/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/post_install_network_config_arc/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/download_config_files/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/download_config_files/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/download_config_files/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/download_config_files/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/download_config_files/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/download_config_files/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/koan_environment/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/koan_environment/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/koan_environment/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/koan_environment/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/koan_environment/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/koan_environment/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/redhat_register/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/redhat_register/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/redhat_register/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/redhat_register/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/redhat_register/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/redhat_register/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/post_arc_rocky9/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/post_arc_rocky9/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/post_arc_rocky9/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/post_arc_rocky9/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/post_arc_rocky9/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/post_arc_rocky9/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/cobbler_register/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/cobbler_register/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/cobbler_register/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/cobbler_register/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/cobbler_register/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/cobbler_register/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/post_anamon/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/post_anamon/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/post_anamon/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/post_anamon/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/post_anamon/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/post_anamon/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/autoinstall_done/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/autoinstall_done/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/autoinstall_done/rocky90-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_system/autoinstall_done/shuttle-sbl.lab.local
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_profile/autoinstall_done/rocky9-x86_64
[Thread-1363] 2023-01-18T11:21:53 - WARNING | File does not exist: /var/lib/cobbler/snippets/per_distro/autoinstall_done/rocky90-x86_64
[Thread-1364] 2023-01-18T11:22:25 - INFO | REMOTE run_install_triggers; user(?)
[Thread-1364] 2023-01-18T11:22:25 - DEBUG | running python triggers from /var/lib/cobbler/triggers/install/pre/*
[Thread-1364] 2023-01-18T11:22:25 - DEBUG | running python trigger cobbler.modules.installation.pre_puppet
[Thread-1364] 2023-01-18T11:22:25 - DEBUG | running python trigger cobbler.modules.installation.pre_clear_anamon_logs
[Thread-1364] 2023-01-18T11:22:25 - INFO | Cleared Anamon logs for "shuttle-sbl.lab.local".
[Thread-1364] 2023-01-18T11:22:25 - DEBUG | running python trigger cobbler.modules.installation.pre_log
[Thread-1364] 2023-01-18T11:22:25 - DEBUG | running shell triggers from /var/lib/cobbler/triggers/install/pre/*
[Thread-1364] 2023-01-18T11:22:25 - DEBUG | shell triggers finished successfully
[Thread-1368] 2023-01-18T11:23:38 - DEBUG | REMOTE CLI Authorized; user(?)
[Thread-1372] 2023-01-18T11:24:09 - DEBUG | REMOTE CLI Authorized; user(?)
[Thread-1374] 2023-01-18T11:27:51 - INFO | REMOTE disable_netboot; user(?); name(shuttle-sbl.lab.local)
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | running python triggers from /var/lib/cobbler/triggers/add/system/pre/*
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | running shell triggers from /var/lib/cobbler/triggers/add/system/pre/*
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | shell triggers finished successfully
[Thread-1374] 2023-01-18T11:27:51 - INFO | generating: /var/lib/tftpboot/pxelinux.cfg/shuttle-sbl.lab.local
[Thread-1374] 2023-01-18T11:27:51 - INFO | generating: /var/lib/tftpboot/grub/system/shuttle-sbl.lab.local
[Thread-1374] 2023-01-18T11:27:51 - INFO | Successfully removed "/var/lib/tftpboot/grub/system_link/shuttle-sbl.lab.local"
[Thread-1374] 2023-01-18T11:27:51 - INFO | generating: /var/lib/tftpboot/pxelinux.cfg/01-80-ee-73-f3-8e-f9
[Thread-1374] 2023-01-18T11:27:51 - INFO | generating: /var/lib/tftpboot/grub/system/80:ee:73:f3:8e:f9
[Thread-1374] 2023-01-18T11:27:51 - INFO | Successfully removed "/var/lib/tftpboot/grub/system_link/shuttle-sbl.lab.local"
[Thread-1374] 2023-01-18T11:27:51 - INFO | Writing template files for shuttle-sbl.lab.local
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | running python triggers from /var/lib/cobbler/triggers/change/*
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | running python trigger cobbler.modules.scm_track
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | running python trigger cobbler.modules.managers.genders
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | running shell triggers from /var/lib/cobbler/triggers/change/*
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | shell triggers finished successfully
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | running python triggers from /var/lib/cobbler/triggers/add/system/post/*
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | running python trigger cobbler.modules.nsupdate_add_system_post
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | running shell triggers from /var/lib/cobbler/triggers/add/system/post/*
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | shell triggers finished successfully
[Thread-1374] 2023-01-18T11:27:51 - INFO | sync_dhcp
[Thread-1374] 2023-01-18T11:27:51 - INFO | generating /etc/dhcp/dhcpd.conf
[Thread-1374] 2023-01-18T11:27:51 - INFO | running: ['/usr/sbin/dhcpd', '-t', '-q']
[Thread-1374] 2023-01-18T11:27:51 - INFO | received on stdout:
[Thread-1374] 2023-01-18T11:27:51 - DEBUG | received on stderr:
[Thread-1374] 2023-01-18T11:27:51 - INFO | running: ['systemctl', 'restart', 'dhcpd']
[Thread-1374] 2023-01-18T11:27:52 - INFO | received on stdout:
[Thread-1374] 2023-01-18T11:27:52 - DEBUG | received on stderr:
[Thread-1375] 2023-01-18T11:27:52 - INFO | REMOTE generate_autoinstall; user(?)
````

### Screenshots

The following Picture shows /var/lib/tftpboot/pxelinux.cfg/shuttle-sbl.lab.local (left before installation, right during loop)
![image](https://user-images.githubusercontent.com/86296728/213153960-caa5c209-fede-41d0-92ee-98352cab64ae.png)

The following Picture shows /var/lib/tftpboot/grub/system/shuttle-sbl.lab.local (left before installation, right during loop)
![image](https://user-images.githubusercontent.com/86296728/213154071-f8de6d9d-a9ac-46e8-b77e-543f93c0b2b6.png)

#### Additional Files
/etc/cobbler/boot_loader_conf/grub.template
```
#if $varExists('system_name')
set system="$system_name"
set timeout=5
#if $netboot_enabled
set default='$menu_name'
#else
set default='local'
#end if
#end if
menuentry '$menu_name' --class gnu-linux --class gnu --class os {
  echo 'Loading kernel ...'
  linuxefi $kernel_path $kernel_options
  echo 'Loading initial ramdisk ...'
  initrdefi $initrd_path
  echo '...done'
}
```
/etc/cobbler/boot_loader_conf/pxe.template
```
#if $breed == "vmware"
#set $append_line="append -c " + $img_path + "/cobbler-boot.cfg" + $append_line
#end if
#set $system_local=False
#if $varExists('system_name')
#if not $netboot_enabled
#set $system_local=True
totaltimeout 0
#else
timeout 1
#if $breed == "vmware"
#set $append_line=$append_line + " " + $img_path + "/vmkboot.gz --- " + $img_path + "/vmkernel.gz --- " + $img_path + "/sys.vgz --- " + $img_path + "/cim.vgz --- " + $img_path + "/ienviron.vgz --- " + $img_path + "/install.vgz"
#end if
#end if
prompt 0
default $menu_name
ontimeout $menu_name
#end if
#if not ($arch in ["ppc", "ppc64"] and $system_local)
LABEL $menu_name
        MENU LABEL $menu_label
#if $system_local
        localboot -1
#else
        #kernel $kernel_path
        linuxefi $kernel_path $kernel_options
        initrdefi $initrd_path

#if $breed != "windows"
        #$append_line
        #ipappend 2
#end if
#end if
#end if
```
/etc/cobbler/settings.yaml
```
# Cobbler settings file
# Docs for this file can be found at: https://cobbler.readthedocs.io/en/latest/cobbler-conf.html

allow_duplicate_hostnames: false
allow_duplicate_ips: false
allow_duplicate_macs: false
allow_dynamic_settings: false
always_write_dhcp_entries: false
anamon_enabled: false
auth_token_expiration: 3600
authn_pam_service: login
auto_migrate_settings: false
autoinstall: default.ks
autoinstall_snippets_dir: /var/lib/cobbler/snippets
autoinstall_templates_dir: /var/lib/cobbler/templates
bind_chroot_path: ''
bind_manage_ipmi: true
bind_master: 127.0.0.1
bind_zonefile_path: /var/named
boot_loader_conf_template_dir: /etc/cobbler/boot_loader_conf
bootloaders_dir: /var/lib/cobbler/loaders
bootloaders_formats:
  IA64: {binary_name: bootia64.efi}
  aarch64: {binary_name: grubaa64.efi}
  arm: {binary_name: bootarm.efi}
  arm64-efi:
    binary_name: grubaa64.efi
    extra_modules: [efinet]
  i386-efi: {binary_name: bootia32.efi}
  i386-pc-pxe:
    binary_name: grub.0
    extra_modules: [chain, pxe, biosdisk]
    mod_dir: i386-pc
  i686: {binary_name: bootia32.efi}
  powerpc-ieee1275:
    binary_name: grub.ppc64le
    extra_modules: [net, ofnet]
  x86_64-efi:
    binary_name: grubx86.efi
    extra_modules: [chain, efinet]
bootloaders_ipxe_folder: /usr/share/ipxe/
bootloaders_modules: [btrfs, ext2, xfs, jfs, reiserfs, all_video, boot, cat, configfile,
  echo, fat, font, gfxmenu, gfxterm, gzio, halt, iso9660, jpeg, linux, loadenv, minicmd,
  normal, part_apple, part_gpt, part_msdos, password_pbkdf2, png, reboot, search,
  search_fs_file, search_fs_uuid, search_label, sleep, test, 'true', video, mdraid09,
  mdraid1x, lvm, serial, regexp, tr, tftp, http, luks, gcry_rijndael, gcry_sha1, gcry_sha256]
bootloaders_shim_file: shim[a-zA-Z0-9]*\.efi
bootloaders_shim_folder: /boot/efi/EFI/*/
build_reporting_email: [root@localhost]
build_reporting_enabled: false
build_reporting_ignorelist: []
build_reporting_sender: ''
build_reporting_smtp_server: localhost
build_reporting_subject: ''
buildisodir: /var/cache/cobbler/buildiso
cheetah_import_whitelist: [random, re, time, netaddr]
client_use_https: false
client_use_localhost: false
cobbler_master: ''
convert_server_to_ip: false
createrepo_flags: -c cache -s sha
default_name_servers: []
default_name_servers_search: []
default_ownership: [admin]
default_password_crypted: $1$rjkjlws3$wIb4OUshnlwpv5HR.hAYb/
default_template_type: cheetah
default_virt_bridge: xenbr0
default_virt_disk_driver: raw
default_virt_file_size: 5
default_virt_ram: 512
default_virt_type: xenpv
enable_ipxe: false
enable_menu: true
grub2_mod_dir: /usr/lib/grub
grubconfig_dir: /var/lib/cobbler/grub_config
http_port: 80
include: [/etc/cobbler/settings.d/*.settings]
iso_template_dir: /etc/cobbler/iso
jinja2_includedir: /var/lib/cobbler/jinja2
kernel_options: {}
ldap_anonymous_bind: true
ldap_base_dn: DC=example,DC=com
ldap_port: 389
ldap_search_bind_dn: ''
ldap_search_passwd: ''
ldap_search_prefix: uid=
ldap_server: ldap.example.com
ldap_tls: true
ldap_tls_cacertdir: ''
ldap_tls_cacertfile: ''
ldap_tls_certfile: ''
ldap_tls_cipher_suite: ''
ldap_tls_keyfile: ''
ldap_tls_reqcert: ''
manage_dhcp: true
manage_dhcp_v4: true
manage_dhcp_v6: false
manage_dns: false
manage_forward_zones: []
manage_genders: false
manage_reverse_zones: []
manage_rsync: false
manage_tftpd: true
mgmt_classes: []
mgmt_parameters: {from_cobbler: true}
next_server_v4: 192.168.31.13
next_server_v6: fe80::250:56ff:feb1:a8da
nopxe_with_triggers: true
nsupdate_enabled: false
nsupdate_log: /var/log/cobbler/nsupdate.log
nsupdate_tsig_algorithm: hmac-sha512
nsupdate_tsig_key: [cobbler_update_key., hvnK54HFJXFasHjzjEn09ASIkCOGYSnofRq4ejsiBHz3udVyGiuebFGAswSjKUxNuhmllPrkI0HRSSmM2qvZug==]
power_management_default_type: ipmilanplus
proxy_url_ext: ''
proxy_url_int: ''
puppet_auto_setup: false
puppet_parameterized_classes: true
puppet_server: ''
puppet_version: 2
puppetca_path: /usr/bin/puppet
pxe_just_once: true
redhat_management_key: ''
redhat_management_permissive: false
redhat_management_server: xmlrpc.rhn.redhat.com
register_new_installs: false
remove_old_puppet_certs_automatically: false
replicate_repo_rsync_options: -avzH
replicate_rsync_options: -avzH
reposync_flags: --newest-only --delete --refresh --remote-time
reposync_rsync_flags: -rltDv --copy-unsafe-links
restart_dhcp: true
restart_dns: true
run_install_triggers: true
samba_distro_share: DISTRO
scm_push_script: /bin/true
scm_track_author: cobbler <cobbler@localhost>
scm_track_enabled: false
scm_track_mode: git
serializer_pretty_json: false
server: 192.168.31.13
sign_puppet_certs_automatically: false
signature_path: /var/lib/cobbler/distro_signatures.json
signature_url: https://cobbler.github.io/signatures/3.0.x/latest.json
syslinux_dir: /usr/share/syslinux
syslinux_memdisk_folder: /usr/share/syslinux
syslinux_pxelinux_folder: /usr/share/syslinux
tftpboot_location: /var/lib/tftpboot
virt_auto_boot: true
webdir: /var/www/cobbler
webdir_whitelist: [misc, web, webui, localmirror, repo_mirror, distro_mirror, images,
  links, pub, repo_profile, repo_system, svc, rendered, .link_cache]
windows_enabled: false
windows_template_dir: /etc/cobbler/windows
xmlrpc_port: 25151
yum_distro_priority: 1
yum_post_install_mirror: true
yumdownloader_flags: --resolve
```
