### ISSUE TITLE
Document how to create a network bridge

### ISSUE THREAD

**Issue by sli720** [cobbler/cobbler#3406]
Could you please add to the docu how to create a network bridge like described here:

https://access.redhat.com/documentation/de-de/red_hat_enterprise_linux/6/html/deployment_guide/s2-networkscripts-interfaces_network-bridge

I don't know what I'm doing wrong. I create a eno1 device with the following parameters:

```
eno1:
  interfacetype: bridge_slave
  interfacemaster: br0
  macaddress: "<mac>"
```

Then I create the bridge:

```
br0:
  interfacetype: bridge
  ipaddress: "<ip>"
  netmask: "<netmask>"
  static: true
```

But at the end I have an eno1 interface configured as type bridge 

```
DEVICE=eno1
ONBOOT=yes
HWADDR=<mac>
TYPE=Bridge
BRIDGE=br0
HOTPLUG=no
BOOTPROTO=none
```

which is wrong. If I change Type to Ethernet it works. What am I doing wrong?
