### ISSUE TITLE
[Guest][Ubuntu-22.04][Cloud-Init] - Storage customization not working

### ISSUE THREAD

**Issue by NileshChandekar** [cobbler/cobbler#3579]
* Trying to configure the custom layout using user-data [cloud-init] 

```
  storage:
    layout:
      name: lvm
      sizing-policy: largest
    config:
      - type: partition
        id: boot-partition
        device: root-disk
        size: 10%
      - type: partition
        id: root-partition
        size: 10G
      - type: partition
        id: data-partition
        device: root-disk
        size: -1
```
* But its not working. 

### Expectation: 
Should create 
~~~
/home
/var
~~~
other than 
/ and /boot

### Cobbler version
```
[root@localhost pub]# cobbler --version 
Cobbler 3.2.2
  source: ?, ?
  build time: Wed Apr  5 15:54:53 2023
[root@localhost pub]# 
````

### Operating system
~~~
[root@localhost pub]# cat /etc/*release
Rocky Linux release 8.9 (Green Obsidian)
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
Rocky Linux release 8.9 (Green Obsidian)
Rocky Linux release 8.9 (Green Obsidian)
Rocky Linux release 8.9 (Green Obsidian)
[root@localhost pub]# 
~~~
