### ISSUE TITLE
Index profile.arch is not usable

### ISSUE THREAD

**Issue by tpw56j** [cobbler/cobbler#3874]
### Describe the bug

The `profile.arch` index is not updated when:
1. the profile's distro changes
2. the profile's parent profile changes

### Steps to reproduce

1. `cobbler profile edit --distro=test_distro` or `cobbler profile edit --parent=test_profile`

### Expected behavior

The `profile.arch` index should be updated when the distro or parent profile changes.

### Cobbler version

````paste below
Cobbler 3.4.0
````

### Operating system

Any

### Additional information

Workaround:
disable the index in `settings.yaml`
```yaml
memory_indexes:
    profile:
        arch:
            nonunique: true
            disabled: true
```
