### ISSUE TITLE
in LDAP authenticatetion, all authenticate users are authorization (ignoring file users.conf)

### ISSUE THREAD

**Issue by sHaggYcaT** [cobbler/cobbler#541]
I use cobbler-2.2.3-2.el6.noarch and cobbler-web-2.2.3-2.el6.noarch. all users, who authenticate with ldap, logging in cobbler web-interface,  ignoring file /etc/cobbler/users.conf.
# 

```
[root@cobbler-test01 cobbler]# grep -v -e '^#' -e '^$' modules.conf
[authentication]
module = authn_ldap
[authorization]
module = authz_ownership
[dns]
module = manage_bind

[dhcp]
module = manage_isc

[tftpd]
module = manage_in_tftpd
[root@cobbler-test01 cobbler]#

===============

I also try test:

module = authn_ldap 



And this is settings file:

==============
[root@cobbler-test01 cobbler]# cat settings | grep -v '^#' | grep -v '^$' 

---
allow_duplicate_hostnames: 0
allow_duplicate_ips: 0
allow_duplicate_macs: 0
anamon_enabled: 0
authn_pam_service: "login"
build_reporting_enabled: 0
build_reporting_sender: ""
build_reporting_email: [ 'root@localhost' ]
build_reporting_smtp_server: "localhost"
build_reporting_subject: ""
cheetah_import_whitelist:
   - "random"
   - "re"
   - "time"
createrepo_flags: "-c cache -s sha"
default_kickstart: /var/lib/cobbler/kickstarts/default.ks
default_name_servers: []
default_ownership:
    - "admin"
default_password_crypted: "****"
default_template_type: "cheetah"
default_virt_bridge: xenbr0
default_virt_file_size: 5
default_virt_ram: 512
default_virt_type: xenpv
enable_gpxe: 0
enable_menu: 1
func_auto_setup: 0
func_master: overlord.example.org
http_port: 80
kernel_options:
    ksdevice: bootif
    lang: ' '
    text: ~
kernel_options_s390x:
    RUNKS: 1
    ramdisk_size: 40000
    root: /dev/ram0
    ro: ~
    ip: off
    vnc: ~
ldap_server: "***.ru"
ldap_base_dn: "ou=users,***"
ldap_port: 389
ldap_tls: 1
ldap_anonymous_bind: 0
ldap_search_bind_dn: 'uid=cobbler.colo.***,***'
ldap_search_passwd: '***'
ldap_search_prefix: 'uid='
mgmt_classes: []
mgmt_parameters:
   from_cobbler: 1
puppet_auto_setup: 0
sign_puppet_certs_automatically: 0
puppetca_path: "/usr/sbin/puppetca"
remove_old_puppet_certs_automatically: 0
manage_dhcp: 1
manage_dns: 0
bind_chroot_path: ""
bind_master: 127.0.0.1
manage_tftpd: 1
manage_rsync: 0
manage_forward_zones: []
manage_reverse_zones: []
next_server: 10.3.19.17
power_management_default_type: 'ipmitool'
power_template_dir: "/etc/cobbler/power"
pxe_just_once: 0
pxe_template_dir: "/etc/cobbler/pxe"
consoles: "/var/consoles"
redhat_management_type: "off"
redhat_management_server: "xmlrpc.rhn.redhat.com"
redhat_management_key: ""
redhat_management_permissive: 0
register_new_installs: 0
reposync_flags: "-l -m -d"
restart_dns: 1
restart_dhcp: 1
run_install_triggers: 1
scm_track_enabled: 0
scm_track_mode: "git"
server: 10.*.*.*
client_use_localhost: 0
snippetsdir: /var/lib/cobbler/snippets
template_remote_kickstarts: 0
virt_auto_boot: 1
webdir: /var/www/cobbler
xmlrpc_port: 25151
yum_post_install_mirror: 1
yum_distro_priority: 1
yumdownloader_flags: "--resolve"
serializer_pretty_json: 0
[root@cobbler-test01 cobbler]#

```
# 

And, file users.conf write by script in cron (script watch ldap group and paste logings).

Logged in web face ALL users, if login/password true in ldap, ignoring file users.conf
